#!/bin/sh
set -e
cassVer="cassandra-2.0.4"
FilePath="/etc/profile"

# Remove Cassandra Files and Folders
if [ -d "/opt/$cassVer" ]; 
then
	rm -r /opt/$cassVer
fi

if [ -f "/etc/profile.d/cassandra-mgmt-home.sh" ]; then
	rm /etc/profile.d/cassandra-mgmt-home.sh
fi

if [ -f "/etc/init.d/cassandra" ]; 
then 
	rm /etc/init.d/cassandra
fi

# This should add the service to the automatic startup system
sudo update-rc.d -f cassandra remove

# Delete cassandra.pid file from /var/run/cassandra/cassandra.pid
sudo rm -rf /var/run/cassandra

. $FilePath
