#!/bin/bash

# expected paths when in production mode
subutai_conf_base=/etc/subutai
subutai_lib_base=/usr/share/subutai-cli/subutai/libs

# source user overrides and settings
if [ -f ~/.subutairc ]; then
  . ~/.subutairc
fi

# check if the user is using the scripts in test mode
# if the user has specified the TEST_MODE to be true
# and specifies the PROJECT_HOME we use the scripts
# and function libraries from inside the project there.

if [ -n "$TEST_MODE" -a "$TEST_MODE" == "true" ]; then
  export subutai_conf_base="$PROJECT_HOME/src/main/config"
  export subutai_lib_base="$PROJECT_HOME/src/main/scripts"

  . $subutai_lib_base/funcs

  msg_warning "Operating in test mode!!!"
else 
  export subutai_conf_base
  export subutai_lib_base
fi

echo args="$@"


