#!/bin/bash
set -e

FilePath="/etc/profile"
activemqHomeEcho="/opt/apache-activemq-5.9.1"
activemqConf=$activemqHomeEcho"/conf"

if grep -q "export ACTIVEMQ_HOME=" $FilePath
then
        echo "hadoop home is already added!"
else
        echo "hadoop home is being inserted"
        echo "export ACTIVEMQ_HOME="$activemqHomeEcho >> $FilePath
fi
. $FilePath
