#!/bin/sh

# Exit on error
set -e

# Remove Activemq Files and Folders
if [ -d "/opt/apache-activemq-5.9.1" ]; then
        echo "/opt/apache-activemq-5.9.1 exists!"
	rm -r /opt/apache-activemq-5.9.1
else
        echo "/opt/apache-activemq-5.9.1 does not exist!"
fi
#Remove paths and exports from relevant files
FilePath="/etc/profile"
activemqHome="\/opt\/apache-activemq-5.9.1"

if grep -q "export ACTIVEMQ_HOME=" $FilePath
then
        echo "activemq home is being deleted!"
        sed -i "/export ACTIVEMQ_HOME=$activemqHome/d" $FilePath
else
        echo "activemq home does not exist"
fi

if [ -f "/etc/init.d/activemq" ]; then
	rm  /etc/init.d/activemq
fi

if [ -f "/opt/apache-activemq-5.9.1" ]; then
        sudo rm -rf /opt/apache-activemq-5.9.1
fi

. $FilePath
