#!/bin/sh

# Exit on error
set -e

if [ -d "/var/lib/lxc/base-container" ]; then
        echo "/var/lib/lxc/base-container exists!"
	rm -r /var/lib/lxc/base-container
else
        echo "/var/lib/lxc/base-container does not exist!"
fi
