#!/bin/sh

# Exit on error
set -e

BRIDGE="br0"

# Install LXC
tar -xpzf /var/lib/lxc/base-container.tar.gz -C /var/lib/lxc
sed -i 's/lxcbr0/'"$BRIDGE"'/g' /var/lib/lxc/base-container/config
# Remove tar file
rm -rf /var/lib/lxc/base-container.tar.gz
