package org.safehaus.subutai.wol.ui;


import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.*;
import com.vaadin.ui.themes.Runo;
import org.safehaus.subutai.common.protocol.Disposable;
import org.safehaus.subutai.wol.api.WolManager;


/**
 * Created by emin on 14/11/14.
 */
public class WolForm extends CustomComponent implements Disposable {

    @AutoGenerated
    private Button sendMagicPackageButton;
    @AutoGenerated
    private TextField testTextField;

    private WolUI wolui;

    private WolManager wolManager;

    public WolForm() {
        setHeight( 100, UNITS_PERCENTAGE );

        VerticalLayout verticalLayout = new VerticalLayout();
        verticalLayout.setSpacing( true );
        verticalLayout.setSizeFull();

        testTextField = new TextField();
        testTextField.setImmediate( false );
        testTextField.setWidth("-1px");
        testTextField.setHeight("-1px");
        testTextField.setMaxLength(15);
        testTextField.setCaption("MacId");
        verticalLayout.addComponent( testTextField );

        sendMagicPackageButton = createSendMagicPackageButton();
        verticalLayout.addComponent( sendMagicPackageButton );

        TabSheet sheet = new TabSheet();
        sheet.setStyleName( Runo.TABSHEET_SMALL );
        sheet.setSizeFull();
        sheet.addTab( new Button("SendMagicPackage"), "WakeOnLAN" );
        verticalLayout.addComponent( sheet );
        setCompositionRoot( verticalLayout );
    }

    private Button createSendMagicPackageButton()
    {
        sendMagicPackageButton = new Button();
        sendMagicPackageButton.setCaption( "SendMagicPackage" );
        sendMagicPackageButton.setImmediate( false );
        sendMagicPackageButton.setWidth( "-1px" );
        sendMagicPackageButton.setHeight( "-1px" );

        sendMagicPackageButton.addClickListener( new Button.ClickListener()
        {
            @Override
            public void buttonClick( final Button.ClickEvent clickEvent ) {

                wolui.getWolManager().sendMagicPackagebyMacId("aa:bb:cc:dd:ee:ff");
             //   testTextField.setValue(wolManager.sendMagicPackagebyMacId("aa:bb:cc:dd:ee"));
            }
        } );

        return sendMagicPackageButton;
    }

    @Override
    public void dispose() {

    }
}
