#!/bin/sh

# Exit on error
set -e
. /etc/profile

name="derby"
folderName="db-derby-10.4.2.0-bin"
derbyHomeEcho="/opt/$folderName"
derbyServiceFile="/etc/init.d/$name"
derbyHomeScript="/etc/profile.d/$name-home.sh"
derbyHome="\/opt\/$folderName"

#Remove derby directory if exists
if [ -d "$derbyHomeEcho" ]; then
        echo "$derbyHomeEcho exists!"
	rm -r "$derbyHomeEcho"
else
        echo "$derbyHomeEcho does not exist!"
fi

if [ -f "$derbyServiceFile" ]; then
        echo "$derbyServiceFile exists!"
        rm -r "$derbyServiceFile"
else
        echo "$derbyServiceFile does not exist!"
fi

if [ -f "$derbyHomeScript" ]; then
        echo "$derbyHomeScript exists!"
        rm -r "$derbyHomeScript"
else
        echo "$derbyHomeScript does not exist!"
fi

if [ -f $HIVE_HOME/lib/derbyclient.jar ]; then
	rm $HIVE_HOME/lib/derbyclient.jar
fi
if [ -f $HIVE_HOME/lib/derbytools.jar ]; then
	rm $HIVE_HOME/lib/derbytools.jar
fi
