#!/bin/bash
# Starts, stops, restarts and shows status of hadoop NameNode, DataNodes and SecondaryNameNode.

hadoopVersion=2.3.0

case "$1" in
start)
	start-stop-daemon --start --exec /opt/hadoop-$hadoopVersion/sbin/mr-jobhistory-daemon.sh start historyserver
;;
stop)
	start-stop-daemon --start --exec /opt/hadoop-$hadoopVersion/sbin/mr-jobhistory-daemon.sh stop historyserver
;;
restart)
	$0 stop
	$0 start
;;
status)
	line1=$(ps aux | grep [J]obHistoryServer)
	if [ -n "$line1" ]; then
		echo "JobHistoryServer is Running"
		#exit 0
	else
		echo "JobHistoryServer is NOT Running"
		#exit 1
	fi
;;
*)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac
