#!/bin/bash
# Starts and stops hadoop JobTracker, and TaskTrackers.

hadoopVersion=2.3.0

case "$1" in
start)
	start-stop-daemon --start --exec /opt/hadoop-$hadoopVersion/sbin/start-yarn.sh
;;
stop)
	start-stop-daemon --start --exec /opt/hadoop-$hadoopVersion/sbin/stop-yarn.sh
;;
restart)
	$0 stop
	$0 start
;;
status)
	line=$(ps aux | grep [R]esourceManager)
	line2=$(ps aux | grep [N]odeManager)

	#if pidof -o %PPID DataNode > /dev/null; then
	if [ -n "$line" ]; then
		echo "ResouceManager is Running"
		#exit 0
	else
		echo "ResouceManager is NOT Running"
		#exit 1
	fi
	
	if [ -n "$line2" ]; then
                echo "NodeManager is Running"
                #exit 0
        else
                echo "NodeManager is NOT Running"
                #exit 1
        fi
;;
*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac
