#!/bin/bash
# Starts, stops, restarts and shows status of hadoop NameNode, DataNodes and SecondaryNameNode.

hadoopVersion=2.3.0

case "$1" in
start)
	start-stop-daemon --start --exec /opt/hadoop-$hadoopVersion/sbin/start-dfs.sh
;;
stop)
	start-stop-daemon --start --exec /opt/hadoop-$hadoopVersion/sbin/stop-dfs.sh
;;
restart)
	$0 stop
	$0 start
;;
status)
	line1=$(ps aux | grep [N]ameNode)
	line2=$(ps aux | grep -c [N]ameNode)
	line3=$(ps aux | grep [D]ataNode)
	substring="SecondaryNameNode"
	
	#if pidof -o %PPID DataNode > /dev/null; then
	#Check if the output is empty or not
	if [ -n "$line1" ]; then
		#Check if the output contains specific substring
		if [[ $line1 =~ .*$substring.* ]]; then
  			echo "SecondaryNameNode is Running";
			#Check if output is not less than 2
			if [[ "$line2" -lt 2 ]];
			then
				echo "NameNode is NOT Running"
			else
				echo "NameNode is Running"
			fi
		else
			echo "NameNode is Running!(SecondaryNameNode is not running on this machine)"
		fi
	else
              	echo "NameNode is NOT Running"
        	echo "SecondaryNameNode is NOT Running"
	fi
	
	if [ -n "$line3" ]; then
		echo "DataNode is Running"
	else
		echo "DataNode is NOT Running"
	fi
;;
*)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac
