#!/bin/bash 
set -e

hbaseVersion=0.98.3
hbaseConf="/etc/hbase/"

# Remove HBase Files and Folders
if [ -d "/opt/hbase-$hbaseVersion" ]; then
	rm -r /opt/hbase-$hbaseVersion
fi

#Remove paths and exports from relevant files
FilePath="/etc/profile"

if [ -f "/etc/profile.d/hbase-home.sh" ]; then
	rm /etc/profile.d/hbase-home.sh
fi

. $FilePath
