#!/bin/sh 
set -e
# Remove HBase Files and Folders
if [ -d "/opt/hbase-0.94.16" ]; then
	rm -r /opt/hbase-0.94.16
fi

#Remove paths and exports from relevant files
FilePath="/etc/profile"

if [ -f "/etc/profile.d/hbase-home.sh" ]; then
	rm /etc/profile.d/hbase-home.sh
fi

. $FilePath
