#!/bin/bash 
set -e
FilePath="/etc/profile"

hbaseVersion=0.98.3
hbaseConf="/etc/hbase"
hbaseHome="/opt/hbase-$hbaseVersion/"

escape_characters()
{
	temp_value=$1
	#echo "Escaping some special characters like '/' for name:" $temp_name "and value:" $temp_value	
	escaped_value=$(echo $temp_value | sed -e 's/\//\\\//g')
	#echo "Escaped Value:" $escaped_value  
}

# Replace the comment with the real export in the file
if [[ "x$JAVA_HOME" == "x" ]];
then
    sed -i 's/# export JAVA_HOME=.*/export JAVA_HOME=\/usr\/lib\/jvm\/java-1.7.0-openjdk-amd64/g' $hbaseConf/hbase-env.sh
else
    escape_characters $JAVA_HOME
    echo "Using JAVA_HOME:" $JAVA_HOME
    sed -i 's/# export JAVA_HOME=.*/export JAVA_HOME='$escaped_value'/g' $hbaseConf/hbase-env.sh
fi

. $FilePath


# Create symlink to configuration files
ln -sf $hbaseConf/* $hbaseHome/conf/

# default configuration for hbase
/opt/hbase-$hbaseVersion/bin/hbase-property.sh add hbase-site.xml hbase.rootdir hdfs://localhost:8020/hbase
/opt/hbase-$hbaseVersion/bin/hbase-property.sh add hbase-site.xml hbase.master localhost:60000
/opt/hbase-$hbaseVersion/bin/hbase-property.sh add hbase-site.xml hbase.zookeeper.property.dataDir /opt/hbase-$hbaseVersion/zookeeper
/opt/hbase-$hbaseVersion/bin/hbase-property.sh add hbase-site.xml hbase.zookeeper.property.clientPort 2181
/opt/hbase-$hbaseVersion/bin/hbase-property.sh add hbase-site.xml hbase.zookeeper.quorum localhost
/opt/hbase-$hbaseVersion/bin/hbase-property.sh add hbase-site.xml hbase.cluster.distributed true

# set hbase_manages_zk environment variable inside hbase-env.sh
sed -i 's/# export HBASE_MANAGES_ZK=.*/export HBASE_MANAGES_ZK=true/g' $hbaseConf/hbase-env.sh
