#!/bin/sh 
set -e
FilePath="/etc/profile"

hbaseVersion=0.98.3
hbaseConf="/etc/hbase"

escape_characters()
{
	temp_value=$1
	#echo "Escaping some special characters like '/' for name:" $temp_name "and value:" $temp_value	
	escaped_value=$(echo $temp_value | sed -e 's/\//\\\//g')
	#echo "Escaped Value:" $escaped_value  
}

# Replace the comment with the real export in the file
if [ "x$JAVA_HOME" = "x" ];
then
    sed -i 's/export JAVA_HOME=.*/export JAVA_HOME=\/usr\/lib\/jvm\/java-1.7.0-openjdk-amd64/g' $hbaseConf/hbase-env.sh
else
    escape_characters $JAVA_HOME
    echo "Using JAVA_HOME:" $JAVA_HOME
    sed -i 's/export JAVA_HOME=.*/export JAVA_HOME='$escaped_value'/g' $hbaseConf/hbase-env.sh
fi

. $FilePath


# default configuration for hbase
hbase-property.sh add hbase-site.xml hbase.rootdir hdfs://localhost:8020/hbase
hbase-property.sh add hbase-site.xml hbase.master localhost:60000
hbase-property.sh add hbase-site.xml hbase.zookeeper.property.dataDir /opt/hbase-$hbaseVersion/zookeeper
hbase-property.sh add hbase-site.xml hbase.zookeeper.property.clientPort 2181
hbase-property.sh add hbase-site.xml hbase.zookeeper.quorum localhost
hbase-property.sh add hbase-site.xml hbase.cluster.distributed true