#!/bin/bash
set -e

cd /opt/subutai-gpg/libgpg-error-1.17
echo "Installing libgpg-error-1.17 ..."
./configure > /dev/null 2>&1
make install > /dev/null 2>&1

cd /opt/subutai-gpg/libgcrypt-1.6.2
echo "Installing libgcrypt-1.6.2 ..."
./mkinstalldirs
./configure > /dev/null 2>&1
make install > /dev/null 2>&1

cd /opt/subutai-gpg/libksba-1.3.2
echo "Installing libksba-1.3.2 ..."
./configure > /dev/null 2>&1
make install > /dev/null 2>&1

cd /opt/subutai-gpg/libassuan-2.2.0
echo "Installing libassuan-2.2.0 ..."
./configure > /dev/null 2>&1
make install > /dev/null 2>&1

cd /opt/subutai-gpg/npth-1.1
echo "Installing npth-1.1 ..."
./configure > /dev/null 2>&1
make install > /dev/null 2>&1

cd /opt/subutai-gpg/gnupg-2.1.1
echo "Installing gnupg-2.1.1 ..."
./configure > /dev/null 2>&1
make install > /dev/null 2>&1


insertToBashrc(){
    local file=$HOME/.bashrc
    local search="SSH_AUTH_SOCK="
    if ! grep "$search" $file; then
		echo "SSH_AUTH_SOCK="$HOME"/.gnupg/S.gpg-agent.ssh" >> $file
		echo "export SSH_AUTH_SOCK" >> $file
    fi
}

configureLibs(){
    if [ ! -f /etc/ld.so.conf.d/gpg2.conf ]; then
        touch /etc/ld.so.conf.d/gpg2.conf
    fi
    local file=/etc/ld.so.conf.d/gpg2.conf
    local search="/usr/local/lib"
    if ! grep "$search" $file; then
		echo "/usr/local/lib" >> $file
	fi
    echo "Configuring gnupg-2.1.1 libraries ..."
    ldconfig -v > /dev/null 2>&1
}

insertToBashrc 
configureLibs
