#!/bin/bash

# --------------------------------------------------------------------------
# Bunch-O BTRFS convenience operations
# --------------------------------------------------------------------------

function fs_umount_partitions {
  local src="$1"
  # umount all the partitions
  umount "$HOME/.local/lxc-data/$src-home" > /dev/null 2>&1
  umount "$HOME/.local/lxc-data/$src-var" > /dev/null 2>&1
  umount "$HOME/.local/lxc/$src-opt" > /dev/null 2>&1
  umount "$HOME/.local/share/lxc/$src/rootfs" > /dev/null 2>&1
}

function fs_send_recv_clone {
  local parent="$1"
  local tmp_path="$HOME/.local/tmpdir/"
  local tmp_parent="$tmp_path$parent"
  mkdir -p $HOME/.local/tmpdir/$parent
  sudo btrfs send /lxc-data/$parent-home > $tmp_parent-home.delta
  sudo btrfs send /lxc-data/$parent-var > $tmp_parent-var.delta
  sudo btrfs send /lxc/$parent-opt > $tmp_parent-opt.delta
  sudo btrfs send /var/lib/lxc/$parent/rootfs > $tmp_parent-rootfs.delta
  sudo btrfs receive $tmp_path$parent -f $tmp_parent-rootfs.delta
  sudo btrfs receive $tmp_path -f $tmp_parent-opt.delta
  sudo btrfs receive $tmp_path -f $tmp_parent-var.delta
  sudo btrfs receive $tmp_path -f $tmp_parent-home.delta
  rm $tmp_parent-*.delta
}

function fs_volume_create_sudo {
  local dst_home="$1"
  sudo btrfs subvolume create $dst_home 1>/dev/null
}
function fs_volume_create {
  local dst_home="$1"
  btrfs subvolume create $dst_home 1>/dev/null
}

function fs_volume_delete {
  local src="$1"  
  sudo btrfs subvolume delete $HOME/.local/share/lxc/$src/ 1>/dev/null
}

function fs_is_read_only {
  local item="$1"
  if [ -z "`sudo btrfs property get -ts /var/lib/lxc/$item/rootfs | grep true`" ]; then
    echo 1
  else
    echo 0
  fi
}

# rename datasets and set mount point for rootfs
function fs_rename_datasets_set_mount_point {
  local src="$1"
  local dst="$2"
  local dst_rootfs="$3"
  mv "$HOME/.local/lxc-data/$src-home" "$HOME/.local/lxc-data/$dst-home"
  mv "$HOME/.local/lxc-data/$src-var"  "$HOME/.local/lxc-data/$dst-var"
  mv "$HOME/.local/lxc/$src-opt" "$HOME/.local/lxc/$dst-opt"
  mv "$HOME/.local/share/lxc/$src/rootfs" "$HOME/.local/share/lxc/$dst/"
}

function fs_find_parent_dir {
  local parent="$1"
  lxc-info -n $parent > /dev/null 2>&1
  if [ $? == 0 ]; then
    echo "$HOME"
  fi
}
function fs_take_snapshot_from_parent {
  local parent="$1"
  local child_ds="$2"
  lxc-info -n $parent > /dev/null 2>&1
  if [ $? == 0 ]; then
    sudo btrfs subvolume snapshot $HOME/.local/share/lxc/$parent/rootfs $HOME/.local/share/lxc/$child_ds > /dev/null 2>&1
    #sudo cp -R  $HOME/.local/share/lxc/$parent/rootfs/ $HOME/.local/share/lxc/$child_ds
  else
    sudo btrfs subvolume snapshot $HOME/.local/tmpdir/$parent/rootfs $HOME/.local/share/lxc/$child_ds > /dev/null 2>&1
    #sudo cp -R  /var/lib/lxc/$parent/rootfs $HOME/.local/share/lxc/$child_ds
  fi
}
function fs_clone {
  local parent_snap=`echo "$1" | awk -F"/" '{print $2}' | awk -F"@" '{print $1}'`
  local child_ds=`echo "$2" | awk -F"/" '{print $2}'`
  local parent_name=`echo $parent_snap | awk -F "-" '{print $1}'`
  local parent_dir=`fs_find_parent_dir $parent_name`
  local lxc_path=`lxc_find_parent_dir $parent_name`
  local prefix=""

  if [[ $lxc_path =~ "/var/lib/lxc" ]]; then
     prefix="$HOME/.local/tmpdir"
  else
     prefix="$HOME/.local/"
     if [[ "$1" =~ "var" ]] || [[ "$1" =~ "home" ]]; then
       prefix="$prefix/lxc-data"
     elif [[ "$1" =~ "opt" ]]; then
       prefix="$prefix/lxc"
     fi
  fi

  if [[ "$1" =~ "var" ]] || [[ "$1" =~ "home" ]]; then
    sudo btrfs subvolume snapshot $prefix/$parent_snap $HOME/.local/lxc-data/$child_ds > /dev/null 2>&1
    #sudo cp -R $parent_dir/lxc-data/$parent_snap $HOME/.local/lxc-data/$child_ds > /dev/null 2>&1
  elif [[ "$1" =~ "opt" ]]; then
    sudo btrfs subvolume snapshot $prefix/$parent_snap $HOME/.local/lxc/$child_ds > /dev/null 2>&1
    #sudo cp -R $parent_dir/lxc/$parent_snap $HOME/.local/lxc/$child_ds > /dev/null 2>&1
  else
    rm -rf /$HOME/.local/share/lxc/$child_ds/rootfs
    fs_take_snapshot_from_parent $parent_snap $child_ds
  fi
}

function fs_set_mountpoint {
  local child_roofs="$1"
  local child="$2"
}

function fs_addmount {
  local name=$1
  local mount=$2
  local zpool=$3
  local dataset=$zpool/$name-$mount

  echo Creating $dataset dataset for $mount mount entry
  sudo btrfs subvolume create /$dataset > /dev/null 2>&1

  if [ -z "`sudo btrfs subvolume list /$dataset`" ]; then
    echo Could not create $dataset dataset
    exit 1
  else
    echo Created $dataset dataset, adding $mount mount entry
    echo lxc.mount.entry = /$dataset $mount none bind,rw 0 0 \
         >> /var/lib/lxc/$name/config
  fi
  echo Copying $mount data from rootfs to new $dataset dataset
  pushd .
  local mountpath=/var/lib/lxc/$name/rootfs/$mount
  cd $mountpath

  if [ -n "`sudo ls -A $mountpath`" ]; then
    # We use tar to preserve permissions: do NOT use cp or mv
    tar -c * | tar -x -C /$dataset
    echo Deleting $mount contents from rootfs
    rm -rf /var/lib/lxc/$name/rootfs/$mount/*
  else
    echo Nothing within $mountpath, abandoning copy
  fi

  popd
  # Time to Snapshot and Apply Holds
  sudo btrfs subvolume snapshot -r /$dataset /$dataset-2 > /dev/null 2>&1
  sudo btrfs subvolume delete /$dataset > /dev/null 2>&1
  mv /$dataset-2 /$dataset
  return
}
#snaphost ll holds on clone's rootfs
function fs_snap_hold_readonly {
  local lxc_template="$1"
  sudo btrfs property set -ts $HOME/.local/share/lxc/$lxc_template/rootfs/ ro true
  sudo btrfs property set -ts $HOME/.local/lxc/$lxc_template-opt ro true
  sudo btrfs property set -ts $HOME/.local/lxc-data/$lxc_template-var ro true
  sudo btrfs property set -ts $HOME/.local/lxc-data/$lxc_template-home ro true
}

function fs_recv {
  local template="$1"
  local deltas="$2"
  local lxc_rootfs="$3"
  rm -rf $HOME/.local/share/lxc/$template/rootfs
  sudo btrfs receive $HOME/.local/share/lxc/$template < $deltas/rootfs.delta
  sudo btrfs receive $HOME/.local/lxc < $deltas/opt.delta
  sudo btrfs receive $HOME/.local/lxc-data/ < $deltas/var.delta
  sudo btrfs receive $HOME/.local/lxc-data/ < $deltas/home.delta
  sudo btrfs property set -ts $HOME/.local/share/lxc/$template/rootfs/ ro true
  sudo btrfs property set -ts $HOME/.local/lxc/$template-opt ro true
  sudo btrfs property set -ts $HOME/.local/lxc-data/$template-var ro true
  sudo btrfs property set -ts $HOME/.local/lxc-data/$template-home ro true
}

#generate delta images of all filesystems
function fs_send {
  local parent="$1"
  local container="$2"
  local deltas="$3"
  if [ $parent == "master" ] 
  then
  (sudo btrfs send -p "$HOME/.local/tmpdir/$parent/rootfs" "$HOME/.local/share/lxc/$container/rootfs" > "$deltas/rootfs.delta") > /dev/null 2>&1
  (sudo btrfs send -p "$HOME/.local/tmpdir/$parent-opt" "$HOME/.local/lxc/$container-opt" > "$deltas/opt.delta") > /dev/null 2>&1
  (sudo btrfs send -p "$HOME/.local/tmpdir/$parent-var" "$HOME/.local/lxc-data/$container-var" > "$deltas/var.delta") > /dev/null 2>&1
  (sudo btrfs send -p "$HOME/.local/tmpdir/$parent-home" "$HOME/.local/lxc-data/$container-home" > "$deltas/home.delta") > /dev/null 2>&1
  else
    (sudo btrfs send -p "$HOME/.local/share/lxc/$parent/rootfs" "$HOME/.local/share/lxc/$container/rootfs" > "$deltas/rootfs.delta") > /dev/null 2>&1
    (sudo btrfs send -p "$HOME/.local/lxc/$parent-opt" "$HOME/.local/lxc/$container-opt" > "$deltas/opt.delta") > /dev/null 2>&1
    (sudo btrfs send -p "$HOME/.local/lxc/$parent-var" "$HOME/.local/lxc-data/$container-var" > "$deltas/var.delta") > /dev/null 2>&1
    (sudo btrfs send -p "$HOME/.local/lxc/$parent-home" "$HOME/.local/lxc-data/$container-home" > "$deltas/home.delta") > /dev/null 2>&1
  fi
}

function fs_remove_mount {
  local child="$1"
  local parent="$2"
  local partition="$3"
  local pool="$4"

  child_ds="$pool/$child-$partition"
  parent_ds="$pool/$parent-$partition"

  if [[ "$pool"  == "lxc" ]]; then
    sudo btrfs subvolume delete $HOME/.local/lxc/$child-$partition > /dev/null 2>&1
  else
    sudo btrfs subvolume delete $HOME/.local/lxc-data/$child-$partition > /dev/null 2>&1
  fi

  # Need to destroy mount
  msg_info "    - \"$child_ds\" dataset destroyed"
}


#release all holds on clone's rootfs snaps and delete snaps
#no need in btrfs
function fs_rls_holds_delete_snaps {
  local clone="$1"
  local snap="$2"
  msg_info "    - \"$snap\" snapshot destroyed"
}

#demote template
function fs_demote_template {
  local temp="$1"  
  local lxc_path="$HOME/.local/share/lxc/$temp"
  sudo btrfs property set -ts $HOME/.local/share/lxc/$temp/rootfs/ ro false
  sudo btrfs property set -ts $HOME/.local/lxc/$temp-opt ro false
  sudo btrfs property set -ts $HOME/.local/lxc-data/$temp-var ro false
  sudo btrfs property set -ts $HOME/.local/lxc-data/$temp-home ro false
  lxc_chown $temp
  cat $HOME/.config/lxc/default.conf >> $lxc_path/config
  cat $lxc_path/config | \
    grep -v "lxc.hook.pre-start" | \
    grep -v "subutai.template.package" | \
    grep -v "subutai.git.uuid" >> $lxc_path/config.new
  rm $lxc_path/config
  mv $lxc_path/config.new $lxc_path/config
  lxc_mapshifting $temp

}

# returns the children of the provided container(arg $1)
function fs_get_children_list {
  local parent="$1"
  local snap=

  # we got a dataset instead of a clone name
  if [ -n "`echo $parent | egrep 'lxc.*/'`" ]; then
    snap="$parent@template"
  else
    snap="lxc/$parent@template"
  fi
  local count=0
  for ds in $(sudo btrfs subvolume list -q $HOME/.local/share/lxc | grep "`sudo btrfs subvolume list -u $HOME/.local/share/lxc | grep $parent/ | awk '{print $9}'`" | awk '{print $11}' | awk -F "/" '{print $(NF-1)}')
  do
    children_list[$count]=`fs_ctnr_from_ds $ds`
    count=`expr $count + 1`
  done

  echo ${children_list[*]}
}


# prints out the children for a ds or container name (arg $1)
# counts and prints out the children
# returns the child count
function fs_get_children {
  local parent="$1"
  local snap=

  # we got a dataset instead of a clone name
  if [ -n "`echo $parent | egrep 'lxc.*/'`" ]; then 
    snap="$parent@template"
  else
    snap="lxc/$parent@template"
  fi

  local count=0
  for ds in $(sudo btrfs subvolume list -q $HOME/.local/share/lxc | grep "`sudo btrfs subvolume list -u $HOME/.local/share/lxc | grep $parent/ | awk '{print $9}'`" | awk '{print $11}' | awk -F "/" '{print $(NF-1)}')
  do
     msg_info "        -> \"`fs_ctnr_from_ds $ds`\" is a child of $parent"
     count=`expr $count + 1`
  done
  return $count
}

# assert snapshot (arg $1) exists, if it does NOT show usage (arg $2)
# warning: exits!
function fs_assert_snap {
  local snap=`echo "$1" | awk -F"/" '{print $2}' | awk -F"@" '{print $1}'`
  local usage="$2"
  local lxc_name=`echo $snap | awk -F"-" '{print $1}'`
  local lxc_path=`lxc_find_parent_dir $lxc_name`
  local prefix=""
  if [[ $lxc_path =~ "/var/lib/lxc" ]]; then
     prefix=""
  else
     prefix="$HOME/.local"
  fi

  if [[ "$1" =~ "home" ]] || [[ "$1" =~ "var" ]]; then
    if [ -z "`sudo btrfs property get -ts $prefix/lxc-data/$snap/ | grep true`" ]; then
        msg_error "Snapshot \"$snap\" does NOT exist!"
        show_usage "$usage"
    fi
  elif  [[ "$1" =~ "opt" ]]; then
    if [ -z "`sudo btrfs property get -ts $prefix/lxc/$snap/ | grep true`" ]; then
      msg_error "Snapshot \"$snap\" does NOT exist!"
      show_usage "$usage"
    fi
  else
    if [ -z "`sudo btrfs property get -ts $prefix/lxc/$snap/rootfs | grep true`" ]; then
      msg_error "Snapshot \"$snap\" does NOT exist!"
      show_usage "$usage"
    fi
  fi
}


# assert dataset (arg $1) does NOT exist, if it does show usage (arg $2)
# warning: exits!
function fs_assert_nods {
  local ds="$1"
  local usage="$2"
  if [[ "$ds" =~ "var" ]] || [[ "$ds" =~ "home" ]]; then
    if [ -n "`sudo btrfs subvolume list $HOME/.local/lxc-data | grep $ds`" ]; then
      msg_info "BTRFS dataset \"$ds\" does NOT exist!"
    fi
  elif [[ "$ds" =~ "opt" ]];then
    if [ -n "`sudo btrfs subvolume list $HOME/.local/lxc | grep $ds`" ]; then
      msg_info "BTRFS dataset \"$ds\" does NOT exist!"
     fi
  else
    if [ -n "`sudo btrfs subvolume list $HOME/.local/share/lxc/ | grep $ds`" ]; then
      msg_info "BTRFS dataset \"$ds\" does NOT exist!"
    fi
  fi
}


# assert dataset (arg $1) exists, if it does NOT show usage (arg $2)
# warning: exits!
function fs_assert_ds {
  local ds="$1"
  local usage="$2"
  if [[ "$ds" =~ "var" ]] || [[ "$ds" =~ "home" ]]; then
    if [ -z "`sudo btrfs subvolume list /lxc-data | grep $ds`" ]; then
      msg_error "BTRFS dataset \"$ds\" does NOT exist!"
      show_usage "$usage"
    fi
  elif [[ "$ds" =~ "opt" ]];then
    if [ -z "`sudo btrfs subvolume list /lxc | grep $ds`" ]; then
      msg_error "BTRFS dataset \"$ds\" does NOT exist!"
      show_usage "$usage"
     fi
  else
    if [ -z "`sudo btrfs subvolume list /var/lib/lxc/ | grep $ds`" ]; then
      msg_error "BTRFS dataset \"$ds\" does NOT exist!"
      show_usage "$usage"
    fi
  fi
}


# checks if the container (arg $1) is a template, echo "true"/"false"
function fs_is_template {
  local path1="$HOME/.local/share/lxc"
  local path2="$HOME/.local/tmpdir"
  local path3="/var/lib/lxc"
  local fs_dir="$path1/$1/rootfs"
  
  if [ -z "`(sudo btrfs property get -ts $fs_dir | grep true) 2>/dev/null`" ]; then
    local  fs_dir1="$path2/$1/rootfs"
    if [ -z "`(sudo btrfs property get -ts $fs_dir1 | grep true) 2>/dev/null`" ]; then
      local  fs_dir2="$path3/$1/rootfs"
      if [ -z "`(sudo btrfs property get -ts $fs_dir2 | grep true) 2>/dev/null`" ]; then
        echo false
      else 
        echo true
      fi
    else
      echo true
    fi
  else
    echo true
  fi
}


# gets the parent of a container
# first argument $1 is the name of the child container
# master returns master
function fs_get_parent {
  local c="$1"

  if [ "$c" == "master" ]; then
    echo master
    return
  fi

  local snap=$(sudo btrfs subvolume list -u $HOME/.local/share/lxc | grep `sudo btrfs subvolume list -q $HOME/.local/ | grep $c/ | awk -F" " '{print $9}'` | awk -F" " '{print $11}' | awk -F"/rootfs" '{print $1}' | awk -F"/" '{print $NF}')
  echo `fs_ctnr_from_ds $snap`
}


# extracts the container name from a dataset or a dataset snapshot
function fs_ctnr_from_ds {
  local ds="$1"
  echo $ds | sed -e 's/lxc.*\///' -e 's/@.*//' -e 's/-.*//'
}


# extracts the zpool name from a dataset or a dataset snapshot
function fs_pool_from_ds {
  local ds="$1"
  echo $ds | sed -e 's/\/.*//'
}


# extracts the snapshot name from a dataset snapshot
function fs_snap_from_ds {
  local ds="$1"
  echo $ds | sed -e 's/.*@//'
}


# extracts the partition name from a dataset or a dataset snapshot
function fs_part_from_ds {
  local ds="$1"
  echo $ds | sed -e 's/lxc.*\///' -e 's/@.*//' -e 's/.*-//'
}


# lists all the templates available
function fs_list_templates {
  for item in `lxc-ls`
  do
    if [ ! -z "`sudo btrfs property get -ts $HOME/.local/share/lxc/$item/rootfs | grep true`" ]
    then
       echo $item
    fi
  done
  for item in `ls /var/lib/lxc/ | grep -v -`
  do
    if [ ! -z "`sudo btrfs property get -ts /var/lib/lxc/$item/rootfs | grep true`" ]
    then
       echo *$item
    fi
  done

}
#TODO
function fs_copy_ds {
  local from_ds="$1"

  if [ -n "`echo $from_ds | grep -`" ]; then
    local from_part="`fs_part_from_ds $from_ds`"
  else
    local from_part=""
  fi

  local from_pool="`fs_pool_from_ds $from_ds`"
  local from_lxc="`fs_ctnr_from_ds $from_ds`"
  local parent_lxc="`fs_get_parent $from_lxc`"
  local to_ds="$2"

  if [ -z "$from_part" ]; then
    local parent_ds="$from_pool/$parent_lxc"
  else
    local parent_ds="$from_pool/$parent_lxc-$from_part"
  fi

  local parent_snap="$parent_ds"
  from_ds="`echo $from_ds | awk -F"/" '{print $2}'`"
  from_ds_temp="$from_ds"
  to_ds="`echo $to_ds | awk -F"/" '{print $2}'`"
  to_ds_temp="$to_ds"
  parent_ds="`echo $parent_ds | awk -F"/" '{print $2}'`"
  fs_assert_snap "$parent_snap"
  # make sure the from_ds exists and the to_ds does not
  if [[ "$from_ds" =~ "var" ]] || [[ "$from_ds" =~ "home" ]]; then
    fs_assert_ds "$from_ds"
    fs_assert_nods "$to_ds"
    fs_assert_ds "$parent_ds"
    from_ds="/lxc-data/$from_ds"
    to_ds="/lxc-data/"
    parent_ds="/lxc-data/$parent_ds"
    parent_snap="$parent_ds"
  elif [[ "$from_ds" =~ "opt" ]]; then
    fs_assert_ds "$from_ds"
    fs_assert_nods "$to_ds"
    fs_assert_ds "$parent_ds"
    from_ds="/lxc/$from_ds"
    to_ds="/lxc/"
    parent_ds="/lxc/$parent_ds"
    parent_snap="$parent_ds"
  else
    fs_assert_ds "$from_ds"
    fs_assert_nods "$to_ds"
    fs_assert_ds "$parent_ds"
    from_ds="/var/lib/lxc/$from_ds/rootfs"
    to_ds="/var/lib/lxc/$to_ds"
    parent_ds="/var/lib/lxc/$parent_ds/rootfs"
    parent_snap="$parent_ds"
  fi

  local now=`date +"%m_%d_%Y"`
  local from_snap="$from_ds@$now"

  sudo btrfs subvolume snapshot "$from_ds" "$from_snap"
  local stream="$SUBUTAI_TMPDIR/$parent_lxc$from_lxc$now"
  sudo btrfs property set -ts $from_snap ro true
  sudo btrfs send -p "$parent_snap" "$from_snap" > "$stream"

  if [[ "$from_ds" =~ "/var/lib/lxc/" ]] ; then
    sudo btrfs receive "$to_ds" < "$stream"
    rm -rf "$to_ds/rootfs"
    mv "$to_ds/rootfs@$now" "$to_ds/rootfs"
    sudo btrfs subvolume delete "$from_snap"
    sudo btrfs property set -ts $to_ds/rootfs ro false
  else
    sudo btrfs subvolume delete "$from_ds@$now"
    sudo btrfs receive "$to_ds" < "$stream"
    mv "$from_ds@$now" "$to_ds$to_ds_temp"
    sudo btrfs property set -ts $to_ds$to_ds_temp ro false
  fi
  # cleanup
  rm "$stream"
}
