#!/bin/bash
# HBase init script
#

hbase=hbase-0.94.16

. /opt/$hbase/conf/hbase-env.sh

if [ ! -f "/tmp/*-zookeeper.pid" ]; then
        pidZookeeper=`ls -alt /tmp | grep hbase-.*-zookeeper.pid | head -1 | awk -F " " '{print $9}'`
	echo $pidZookeeper
fi

is_zookeeper_running()
{
    if [ -f /tmp/$pidZookeeper ] && [ "x$pidZookeeper" != "x" ]; then
        pid=`cat /tmp/$pidZookeeper`
        grep -Eq "$CMD_PATT" "/proc/$pid/cmdline" 2>/dev/null && return 1
        return 0
    fi
    return 2 
}

case "$1" in
start)
	/opt/$hbase/bin/hbase-daemons.sh start zookeeper
;;

stop)
	/opt/$hbase/bin/hbase-daemons.sh stop zookeeper
	#pid=`cat /tmp/$pidZookeeper`
	#echo "Stopping HQuorumPeer with pid $pid"
	#start-stop-daemon -K -p "$pidZookeeper" -R TERM/30/KILL/5 >/dev/null 
;;

restart)
        $0 stop
        $0 start
;;

status)
        is_zookeeper_running 
        stat=$?
        case "$stat" in 
        0)
		echo "HQuorumPeer is NOT running"  ;;
	1)
		echo "HQuorumPeer is running"  ;;
	2)
		echo "HQuorumPeer is NOT running and pid file does not exists" ;;
	*)
		echo "Could not find pid of HQuorumPeer!!!"
		
	esac
;;
calc)
	calculate
;;
kill)
	is_zookeeper_running
   	stat=$?
	if [ "$stat" == "1" ]; then
		start-stop-daemon -K -p "/tmp/$pidZookeeper" -R TERM/30/KILL/5 >/dev/null
	fi
	start-stop-daemon -K -p "/tmp/$pidZookeeper" -R TERM/30/KILL/5 >/dev/null
	if [ -f /tmp/$pidZookeeper ];then
		rm /tmp/$pidZookeeper
	fi	
	echo "HQuorumPeer pid file is deleted."
;;
*)
        echo "Usage: $0 {start|stop|restart|status|kill}"
        exit 1
esac

