#!/bin/bash
set -e
sparkVer="spark-1.0.0"

FilePath="/etc/profile"

# Remove Spark Files and Folders
if [ -d "/opt/$sparkVer" ]; then
	rm -r /opt/$sparkVer
fi

if [ -f "/etc/profile.d/spark-home.sh" ]; then
	rm /etc/profile.d/spark-home.sh
fi

if [ -f "/etc/init.d/spark" ]; 
then 
	rm /etc/init.d/spark
fi

if [ -d "/etc/spark" ];
then 
	rm -rf /etc/spark
fi
# Delete spark.pid file from /var/run/spark/spark.pid
sudo rm -rf /var/run/spark

. $FilePath
