package org.safehaus.subutai.common.enums;


public enum ResponseType
{
    EXECUTE_RESPONSE,
    EXECUTE_RESPONSE_DONE,
    REGISTRATION_REQUEST,
    HEARTBEAT_RESPONSE,
    TERMINATE_RESPONSE_DONE,
    TERMINATE_RESPONSE_FAILED,
    EXECUTE_TIMEOUT,
    AGENT_DISCONNECT,
    IN_QUEUE,
    INOTIFY_ACTION_RESPONSE,
    ResponseType, INOTIFY_LIST_RESPONSE
}
