#!/bin/bash 
set -e
FilePath="/etc/profile"
. $FilePath

prestoVersion=0.73
prestoHome="/opt/presto-server-$prestoVersion"
prestoConf="/etc/presto"

if [[ "x$PRESTO_HOME" != "x" ]];
then
        prestoHome=$PRESTO_HOME
fi

# Create etc/ directory under /opt/presto-server
mkdir -p $prestoHome/etc/catalog
# Create symlink to configuration files and scripts
# Create symlink to configuration files and scripts
ln -sf $prestoConf/config.properties $prestoHome/etc/
ln -sf $prestoConf/jvm.config $prestoHome/etc/
ln -sf $prestoConf/log.properties $prestoHome/etc/
ln -sf $prestoConf/node.properties $prestoHome/etc/

ln -sf $prestoConf/catalog/hive.properties $prestoHome/etc/catalog
ln -sf $prestoConf/catalog/jmx.properties $prestoHome/etc/catalog
