#!/bin/sh
# Starts, stops, restarts and show status of Solr.
DESC="Storm UI"
NAME=storm-ui
PIDFILE=/var/run/$NAME/$NAME.pid
CMD_PATT="ui.+"
. /lib/lsb/init-functions


is_running()
{
  if [ -f $PIDFILE ]; then
    pid=`cat $PIDFILE`
    grep -Eq "$CMD_PATT" "/proc/$pid/cmdline" 2>/dev/null && return 0
    return 1
  fi
  return 3
}
case "$1" in
start)
  is_running
  stat=$?
  case "$stat" in
    0) echo $DESC "is already running..." ;;
    1) echo "Could not access pidfile for $DESC" ;;
    *)
      echo "Starting "$DESC" ... "
      [ -e `dirname "$PIDFILE"` ] || \
        install -d -m755 `dirname $PIDFILE`
      DAEMON="/opt/storm-0.8.2/bin/storm"
      ARGS=" ui"
      start-stop-daemon --start --make-pidfile --background --pidfile  "$PIDFILE" --exec "${DAEMON}" -- ${ARGS}
      ;;
  esac
;;

stop)
  is_running
  stat=$?
  case "$stat" in
    0)
      echo "Stopping" $DESC
      echo "PID: " $PIDFILE
      start-stop-daemon -K -p "$PIDFILE" -R TERM/30/KILL/5 >/dev/null
      rm -f "$PIDFILE";;
    1) echo "Could not access pidfile for $DESC" ;;
    *) echo $DESC" is not running..." ;;
  esac
;;

restart)
  $0 stop
  is_running
  stat=$?
  while [ $stat = 0 ];
  do
    is_running
    stat=$?
    sleep 1
  done
  $0 start
;;

status)
  is_running
  stat=$?
  case "$stat" in
    0)
      PID=`cat $PIDFILE`
      log_success_msg "$DESC is running(PID:$PID)" ;;
    1) log_failure_msg "could not access pidfile for $DESC" ;;
    *) log_success_msg "$DESC is not running" ;;
  esac
  exit "$stat"
;;
kill)
  start-stop-daemon -K -p "$PIDFILE" -R TERM/30/KILL/5 >/dev/null
  rm -f "$PIDFILE"
  echo $DESC "is killed..."
;;
*)
  echo "Usage: $0 {start|stop|restart|status}"
  exit 1
esac
