#!/bin/sh
set -e
cassVer="cassandra-2.0.4"

#Remove paths and exports from relevant files
FilePath="/etc/profile"
cassandraHome="\/opt\/$cassVer"
cassandraPath="\/opt\/$cassVer\/bin"

# Remove Cassandra Files and Folders
if [ -d "/opt/$cassVer" ]; 
then
	rm -r /opt/$cassVer
fi

if [ -f "/etc/profile.d/cassandra-home.sh" ];
then
        rm /etc/profile.d/cassandra-home.sh
fi


if [ -f "/etc/init.d/cassandra" ]; 
then 
	rm /etc/init.d/cassandra
fi

# This should add the service to the automatic startup system
sudo update-rc.d -f cassandra remove

# Delete cassandra.pid file from /var/run/cassandra/cassandra.pid
sudo rm -rf /var/run/cassandra

. $FilePath
