#!/bin/bash
set -e
cassVer="cassandra-2.0.9"
FilePath="/etc/profile"

# This should add the service to the automatic startup system
# sudo update-rc.d cassandra defaults

. $FilePath

cassandraHome="/opt/$cassVer"
cassandraConf="/etc/cassandra"

if [[ "x$CASSANDRA_HOME" != "x" ]];
then
        cassandraHome=$CASSANDRA_HOME
fi

if [[ "x$CASSANDRA_CONF_DIR" != "x" ]];
then
        cassandraConf=$CASSANDRA_CONF_DIR
fi


# Create symlink to configuration files and scripts
ln -sf $cassandraConf/* $cassandraHome/conf/
