#!/bin/sh
set -e
cassVer="cassandra-2.0.4"

FilePath="/etc/profile"

# change listen_address, rpc_adress and seeds parameters
# listen_address
# sed -i "s/listen_address: localhost/listen_address: 10.10.10.1/g" /opt/$cassVer/conf/cassandra.yaml

# rpc_address
# sed -i "s/rpc_address: localhost/rpc_address: 10.10.10.1/g" /opt/$cassVer/conf/cassandra.yaml

# seeds
# sed -i "s/- seeds: \"localhost\"/- seeds: \"10.10.10.1\"/g" /opt/$cassVer/conf/cassandra.yaml

# This should add the service to the automatic startup system
sudo update-rc.d cassandra defaults

FilePath="/etc/profile"
. $FilePath

# start cassandra 
# sudo service cassandra start

