#!/bin/sh

# Exit on error
set -e

hadoopVersion=2.3.0

# Remove Hadoop Files and Folders
if [ -d "/opt/hadoop-$hadoopVersion" ]; then
        echo "/opt/hadoop-$hadoopVersion exists!"
	rm -r /opt/hadoop-$hadoopVersion
else
        echo "/opt/hadoop-$hadoopVersion does not exist!"
fi
if ls /var/lib/*hadoop* ; then
        echo "/var/lib/ directory has hadoop files, deleting!"
        rm -r /var/lib/*hadoop*
else
        echo "/var/lib/ directory does not have hadoop files!"
fi

#Remove paths and exports from relevant files
FilePath="/etc/profile"

if [ -f "/etc/profile.d/hadoop2-home.sh" ]; then
	rm  /etc/profile.d/hadoop2-home.sh
fi

if [ -f "/etc/init.d/hadoop-dfs" ]; then
	rm  /etc/init.d/hadoop-dfs
fi
if [ -f "/etc/init.d/hadoop-jobhistory" ]; then
        rm  /etc/init.d/hadoop-jobhistory
fi
if [ -f "/etc/init.d/hadoop-yarn" ]; then
        rm  /etc/init.d/hadoop-yarn
fi

. $FilePath
