#!/bin/sh 
set -e
FilePath="/etc/profile"
nutchHomeEcho="/opt/nutch-1.5"
nutchPath="\/opt\/nutch-1.5\/bin"
nutchPathEcho=$nutchHomeEcho"/bin"
nutchConf=$nutchHomeEcho"/conf"

if grep -q "NUTCH_HOME=" $FilePath
then
        echo "NUTCH_HOME is already in your env variables!"
else
        echo "NUTCH_HOME is inserted"
        echo "export NUTCH_HOME="$nutchHomeEcho >> $FilePath
fi

if grep -q "export PATH=" $FilePath
then
        if grep -q "${nutchPath}" $FilePath
        then
                echo "NUTCH is already inserted to PATH!!!"
        else
                echo "NUTCH is being insterted to PATH!"
                sed -i "s/export PATH=/export PATH=$nutchPath:/1" $FilePath
        fi
else
        echo "export PATH=$PATH:$nutchPathEcho" >> "${FilePath}"
fi

. $FilePath
