#!/bin/bash 
set -e
FilePath="/etc/profile"

. $FilePath

nutchVersion=1.4.4
nutchHome="/opt/nutch-$nutchVersion"
nutchConf="/etc/nutch"

if [[ "x$NUTCH_HOME" != "x" ]];
then
        nutchHome=$NUTCH_HOME
fi

if [[ "x$NUTCH_CONF_DIR" != "x" ]];
then
        nutchConf=$NUTCH_CONF_DIR
fi


# Create symlink to configuration files and scripts
ln -sf $nutchConf/* $nutchHome/conf/
