#!/bin/sh 
set -e
# Remove Nutch Files and Folders
if [ -d "/opt/nutch-1.5" ]; then
	rm -r /opt/nutch-1.5
fi

#Remove paths and exports from relevant files
FilePath="/etc/profile"

if [ -f "/etc/profile.d/nutch-home.sh" ]; then
        rm -r /etc/profile.d/nutch-home.sh
fi

. $FilePath
