#!/bin/bash

function usage {
  echo -----------------------------------------------------------------------
  echo Usage: Exports the master template as a debian package
  echo
  echo "	"subutai-master-export
  echo
  echo -----------------------------------------------------------------------
}


# Plan for exporting a template
# -----------------------------------------------------------------------------
# (1) perform sanity checks first
# (2) generate delta images of all filesystems: 
#     'pool/parent-partition@child' -> 'pool/child-partition@template'
# (3) generate the debian package file from deltas, and package info

function master_export {

  # ---------------------------------------------------------------------------
  # (1) perform some sanity checks
  # ---------------------------------------------------------------------------
  local container="master"
  local debian_package_name=`get_debian_package_name $container`
  local debian_file="$SUBUTAI_TMPDIR/$debian_package_name.deb"
  local debian_root="$SUBUTAI_TMPDIR/$container"

  if [ -f "$debian_file" ]; then
    msg_notice "It seems the debian package file has already been generated"
    msg_error "Run rm -rf $debian_root* and try again"
    exit 1
  fi

  deltas="$debian_root/deltas"
  mkdir -p $deltas

  zfs send "lxc/master@template" > "$deltas/rootfs.delta"
  if [ $? -eq 0 ]; then
    size=`ls -lh $deltas/rootfs.delta | awk '{print $5}'`
    msg_ok "Exported $size delta for rootfs"
  else
    msg_error "Delta generation for rootfs failed"
  fi

  zfs send "lxc/master-opt@template" > "$deltas/opt.delta"
  if [ $? -eq 0 ]; then
    size=`ls -lh $deltas/opt.delta | awk '{print $5}'`
    msg_ok "Exported $size delta for opt"
  else
    msg_error "Delta generation for opt failed"
  fi

  zfs send "lxc-data/master-var@template" > "$deltas/var.delta"
  if [ $? -eq 0 ]; then
    size=`ls -lh $deltas/var.delta | awk '{print $5}'`
    msg_ok "Exported $size delta for var"
  else
    msg_error "Delta generation for opt failed"
  fi

  zfs send "lxc-data/master-home@template" > "$deltas/home.delta"
  if [ $? -eq 0 ]; then
    size=`ls -lh $deltas/home.delta | awk '{print $5}'`
    msg_ok "Exported $size delta for home"
  else
    msg_error "Delta generation for opt failed"
  fi


  # ---------------------------------------------------------------------------
  # (3) generate the debian package from deltas, and package info
  # ---------------------------------------------------------------------------

  lxc_home=/var/lib/lxc/$container
  cp $lxc_home/config $debian_root
  cp $lxc_home/fstab  $debian_root
  cp $lxc_home/packages  $debian_root

  msg_info "Building debian package file for master"

  pkg=`deb_pkg $container`
  # Remove debian root directory after debian package generation
  rm -rf $debian_root

}


function master_export_description {
  echo exports the master template
}


