#!/bin/bash

function get_lxc_list()
{
  echo "`lxc-ls -f | tail -n +3 | cut -d " " -f1`"
}

function destroy_all_lxcs()
{
  for lxc in $1
  do
     if [ "$lxc" != "master" ]
     then
       subutai destroy $lxc > /dev/null 2>&1 && echo "destroy $lxc"
     fi
  done
}

function master_destroy {

  if [ -z "`zfs list lxc/master`" ]; then
    echo No zfs dataset \'lxc/master\' found - aborting ...
    exit 1
  fi

  local container="master"
  local package_name=`get_package_name $container`
  local debian_root="$SUBUTAI_TMPDIR/$container"
  
  # Confirm destroy operation
  echo WARNING: this destroys everything mercilessly
  while true; do
    read -p "Do you wish to destroy master template? [Y/N]" yn
    case $yn in
      [Yy]* ) break;;
      [Nn]* ) exit 1;;
      * ) echo "Please answer yes or no.";;
    esac
  done

  lxc_list="`get_lxc_list`"
  while [ "`echo $lxc_list | wc -w`" -gt 1 ]
  do
    lxc_list="`get_lxc_list`"
    destroy_all_lxcs "$lxc_list"
  done
 
  # Check if the package is installed
  is_package_installed $package_name
  if [ $? == 0  ]; then
    apt-get --assume-yes --force-yes purge $package_name
  fi


  zfs release keep lxc/master-opt@template
  zfs destroy -r lxc/master-opt

  zfs release keep lxc-data/master-var@template
  zfs destroy -r lxc-data/master-var

  zfs release keep lxc-data/master-home@template
  zfs destroy -r lxc-data/master-home

  zfs release keep lxc/master@template
  zfs destroy -r lxc/master
  lxc-destroy -n master
  
  # Remove relevant directories under $SUBUTAI_TMPDIR if any
  rm -rf $debian_root
}


function master_destroy_description {
  echo destroys the master template
}


