#!/bin/bash

modprobe zfs > /dev/null 2>&1;
if [ "$?" == "0" ];then
. $subutai_lib_base/master_zfs_ops
else
. $subutai_lib_base/master_btrfs_ops
fi

function master_import {
  fs_master_import
}


function master_import_description {
  echo imports master template
}


