#!/bin/bash

modprobe zfs > /dev/null 2>&1;
if [ "$?" == "0" ];then
. $subutai_lib_base/master_zfs_ops
else
. $subutai_lib_base/master_btrfs_ops
fi

function usage {
  echo -----------------------------------------------------------------------
  echo Usage: Exports the master template as a debian package
  echo
  echo "	"subutai-master-export
  echo
  echo -----------------------------------------------------------------------
}


# Plan for exporting a template
# -----------------------------------------------------------------------------
# (1) perform sanity checks first
# (2) generate delta images of all filesystems: 
#     'pool/parent-partition@child' -> 'pool/child-partition@template'
# (3) generate the debian package file from deltas, and package info

function master_export {
  fs_master_export
}


function master_export_description {
  echo exports the master template
}


