#!/bin/bash

modprobe zfs > /dev/null 2>&1;
if [ "$?" == "0" ];then
. $subutai_lib_base/master_zfs_ops
else
. $subutai_lib_base/master_btrfs_ops
fi

function setup {
  fs_master_setup
}


function setup_description {
  echo setups up the host
}



