.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SUBUTAI-CLI SECTION "July 13, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
subutai \- program to do something

.SH SYNOPSIS
.B subutai
.RI [ options ] " files" ...
.br

.SH DESCRIPTION
This manual page documents briefly the
.B subutai
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBsubutai\fP is a program that...

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.

.TP
.B \-q, \ quiet
-q is used to suppress fancy tty coloring which might interfere with non-tty based programatic script execution

.TP
.B \-h, \ help
-h is to list all subcommands when used without an argument

.SH COMMAND SET

Here is a list of available subcommands of
.B subutai :

.TP
.B \ list
The subutai list subcommand lists templates and instance containers. By default all templates and containers are "fancy" listed all together. Use the -q global switch to suppress unnecessary output. An optional set of template and or container names can be provided to list as operands to specifically provide information for them. When no operands are provided list provides information on all containers and templates according to filter switches. The following subcommand specific switches are available for use with list:
.TP
	\       -t lists only templates (cannot be used with -c option)
.TP
	\       -c lists only instance containers (cannot be used with the -t option)
.TP
	\       -p list with parent template (can be used for both listing parents of templates and instance containers)
.TP
	\       -a show ancestry (can be used for both listing hierarchy of templates and instance containers)

.TP
.B \ import
Imports a new template. ... write more here

.TP
.B \ export
Exports a new template. ... write more here

.TP
.B \ clone 
Creates a new instance container from a template. Takes two arguments, the parent template, and the new child instance name

.TP
.B \ destroy
Destroys an existing instance container or template. Takes a single argument, the name of the container or template to destroy. Template destruction is constrained to templates that do not have child templates, and have no instance containers. Template destruction does not remove the template from the site, it just removes it from a physical LXC container host. The template may be re-imported into the physical machine.

.TP
.B \ promote
This command converts ("promotes") a instance container into a template

.TP
.B \ demote
This command reverts a promotion. Takes a single argument which must be the name of a template. If the template has child templates or has instance containers it cannot be demoted and will result in an error. Demotion will be complicated because the demotion must take place in a site wide fashion with the assurance that all physical machines in the site have no child template for the template to be demoted. Published global templates cannot be demoted.

.TP
.B \ rename
This command changes the name of an instance container or a non-published template. Takes two arguments, the current name of the instance or template to rename, and the new name for the instance or template. The new name must be site wide unique. The current name must exist. Template renames should only be possible if the template has no child templates or instance containers.


.SH DEV COMMAND SET

Here is a list of available subcommands coming with
.B subutai dev package.
You need to install subutai-cli-dev debian package to be able to use these subcommands. These are packaged separately to prevent accidental use by users.

.TP
.B \ master_create
Creates master template ... write more here

.TP
.B \ master_destroy
Destroys master template ... write more here

.TP
.B \ master_export
Exports master template ... write more here 

.TP
.B \ setup
Setup master template ... write more here 

.SH SEE ALSO
.IR "www.safehaus.org"
