// Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1456546913);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1456547033);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1456546553);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1456546793);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1456546673);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1456547153);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1456546694493");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1456548446493");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1456546439442");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1456550039442");
user_pref("browser.search.countryCode", "KG");
user_pref("browser.search.region", "KG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160209234642");
user_pref("browser.slowStartup.averageTime", 37396);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160209234642");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4,\"addons\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"toggle-button--jid1-aqqsmbyb0a8adgjetpack-mailvelope-options\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"toggle-button--jid1-aqqsmbyb0a8adgjetpack-mailvelope-options\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1456632832933");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1456546494721");
user_pref("datareporting.policy.firstRunTime", "1456546432932");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1668);
user_pref("datareporting.sessions.current.main", 40);
user_pref("datareporting.sessions.current.sessionRestored", 1086);
user_pref("datareporting.sessions.current.startTime", "1456547840469");
user_pref("datareporting.sessions.current.totalTime", 6);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1456546331129,\"a\":76,\"t\":1422,\"c\":true,\"m\":101433,\"fp\":103684,\"sr\":103597}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1456547764005,\"a\":13,\"t\":71,\"c\":true,\"m\":6570,\"fp\":7675,\"sr\":7564}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"jid1-AQqSMBYb0a8ADg@jetpack\":{\"version\":\"1.2.0\",\"type\":\"extension\",\"descriptor\":\"/home/d0m0v0y/Projects/Subutai/Subutai-playbooks/src/test/resources/profilePgpFF/extensions/jid1-AQqSMBYb0a8ADg@jetpack.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1456546914);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455340494000,\"mt\":1455064035000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064750000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064750000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}},\"app-profile\":{\"jid1-AQqSMBYb0a8ADg@jetpack\":{\"d\":\"/home/d0m0v0y/Projects/Subutai/Subutai-playbooks/src/test/resources/profilePgpFF/extensions/jid1-AQqSMBYb0a8ADg@jetpack.xpi\",\"e\":true,\"v\":\"1.2.0\",\"st\":1456547817000}}}");
user_pref("gecko.buildID", "20160209234642");
user_pref("gecko.mstone", "44.0.2");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1456546496);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160209234642");
user_pref("media.gmp-manager.lastCheck", 1456546496);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1456547840);
user_pref("toolkit.telemetry.cachedClientID", "b3ba96af-f51b-4188-a88e-4f4065707c4d");
user_pref("toolkit.telemetry.previousBuildID", "20160209234642");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("xpinstall.signatures.required", false);
