package org.safehaus.subutai.core.peer.ui.forms;


import java.security.KeyStore;
import java.util.List;
import java.util.UUID;

import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import org.safehaus.subutai.common.peer.PeerException;
import org.safehaus.subutai.common.peer.PeerInfo;
import org.safehaus.subutai.common.peer.PeerStatus;
import org.safehaus.subutai.common.security.crypto.keystore.KeyStoreData;
import org.safehaus.subutai.common.security.crypto.keystore.KeyStoreManager;
import org.safehaus.subutai.common.util.StringUtil;
import org.safehaus.subutai.common.util.UUIDUtil;
import org.safehaus.subutai.core.peer.ui.PeerManagerPortalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.cxf.jaxrs.client.WebClient;

import com.google.common.base.Strings;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;


public class PeerRegisterForm extends CustomComponent
{

    private static final Logger LOG = LoggerFactory.getLogger( PeerRegisterForm.class.getName() );
    public final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private Table peersTable;
    @AutoGenerated
    private Button showPeersButton;
    @AutoGenerated
    private Button registerRequestButton;
    @AutoGenerated
    private TextField ipTextField;
    @AutoGenerated
    private TextField servicePortTextField;

    private PeerManagerPortalModule module;


    /**
     * The constructor should first build the main layout, set the composition root and then do any custom
     * initialization. <p/> The constructor will not be automatically regenerated by the visual editor.
     */
    public PeerRegisterForm( final PeerManagerPortalModule module )
    {
        buildMainLayout();
        setCompositionRoot( mainLayout );

        this.module = module;

        showPeersButton.click();
    }


    @AutoGenerated
    private AbsoluteLayout buildMainLayout()
    {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate( false );
        mainLayout.setWidth( "100%" );
        mainLayout.setHeight( "100%" );

        // top-level component properties
        setWidth( "100.0%" );
        setHeight( "100.0%" );

        // peerRegisterLayout
        final AbsoluteLayout peerRegisterLayout = buildAbsoluteLayout_2();
        mainLayout.addComponent( peerRegisterLayout, "top:20.0px;right:0.0px;bottom:-20.0px;left:0.0px;" );

        return mainLayout;
    }


    @AutoGenerated
    private AbsoluteLayout buildAbsoluteLayout_2()
    {

        // common part: create layout
        AbsoluteLayout absoluteLayout = new AbsoluteLayout();
        absoluteLayout.setImmediate( false );
        absoluteLayout.setWidth( "100.0%" );
        absoluteLayout.setHeight( "100.0%" );

        // peerRegistration
        final Label peerRegistration = new Label();
        peerRegistration.setImmediate( false );
        peerRegistration.setWidth( "-1px" );
        peerRegistration.setHeight( "-1px" );
        peerRegistration.setValue( "Peer registration" );
        absoluteLayout.addComponent( peerRegistration, "top:0.0px;left:20.0px;" );

        // IP
        final Label IP = new Label();
        IP.setImmediate( false );
        IP.setWidth( "-1px" );
        IP.setHeight( "-1px" );
        IP.setValue( "IP" );
        absoluteLayout.addComponent( IP, "top:36.0px;left:20.0px;" );

        // ipTextField
        ipTextField = new TextField();
        ipTextField.setImmediate( false );
        ipTextField.setWidth( "-1px" );
        ipTextField.setHeight( "-1px" );
        ipTextField.setMaxLength( 15 );
        absoluteLayout.addComponent( ipTextField, "top:36.0px;left:150.0px;" );

        // port label
        final Label servicePort = new Label();
        servicePort.setImmediate( false );
        servicePort.setWidth( "-1px" );
        servicePort.setHeight( "-1px" );
        servicePort.setValue( "Service Port:" );
        absoluteLayout.addComponent( servicePort, "top:80.0px;left:20.0px;" );

        // servicePortTextField
        servicePortTextField = new TextField();
        servicePortTextField.setImmediate( false );
        servicePortTextField.setWidth( "-1px" );
        servicePortTextField.setHeight( "-1px" );
        servicePortTextField.setMaxLength( 256 );
        absoluteLayout.addComponent( servicePortTextField, "top:80.0px;left:150.0px;" );


        // registerRequestButton
        registerRequestButton = createRegisterButton();
        absoluteLayout.addComponent( registerRequestButton, "top:160.0px;left:20.0px;" );
        registerRequestButton = createRegisterButton();

        // showPeersButton
        showPeersButton = createShowPeersButton();
        absoluteLayout.addComponent( showPeersButton, "top:234.0px;left:20.0px;" );

        // peersTable
        peersTable = new Table();
        peersTable.setCaption( "Peers" );
        peersTable.setImmediate( false );
        peersTable.setWidth( "850px" );
        peersTable.setHeight( "283px" );
        absoluteLayout.addComponent( peersTable, "top:294.0px;left:20.0px;" );

        return absoluteLayout;
    }


    private Button createShowPeersButton()
    {
        showPeersButton = new Button();
        showPeersButton.setCaption( "Show peers" );
        showPeersButton.setImmediate( false );
        showPeersButton.setWidth( "-1px" );
        showPeersButton.setHeight( "-1px" );

        showPeersButton.addClickListener( new Button.ClickListener()
        {
            @Override
            public void buttonClick( final Button.ClickEvent clickEvent )
            {
                populateData();
                peersTable.refreshRowCache();
            }
        } );

        return showPeersButton;
    }


    private void populateData()
    {
        List<PeerInfo> peers = module.getPeerManager().peers();
        peersTable.removeAllItems();
        peersTable.addContainerProperty( "ID", UUID.class, null );
        peersTable.addContainerProperty( "Name", String.class, null );
        peersTable.addContainerProperty( "IP", String.class, null );
        peersTable.addContainerProperty( "Status", PeerStatus.class, null );
        peersTable.addContainerProperty( "ActionsAdvanced", PeerManageActionsComponent.class, null );

        for ( final PeerInfo peer : peers )
        {
            if ( peer == null || peer.getStatus() == null )
            {
                continue;
            }
            PeerManageActionsComponent.PeerManagerActionsListener listener =
                    new PeerManageActionsComponent.PeerManagerActionsListener()

                    {
                        @Override
                        public void OnPositiveButtonTrigger( final PeerInfo peer )
                        {
                            switch ( peer.getStatus() )
                            {
                                case REQUESTED:
                                    peer.setStatus( PeerStatus.APPROVED );
                                    PeerInfo selfPeer;
                                    try
                                    {
                                        selfPeer = getPeerJsonRepresentation( "127.0.0.1", "8181" );
                                        selfPeer.setStatus( PeerStatus.APPROVED );

                                        //************ Send Trust SSL Cert **************************************

                                        KeyStore keyStore;
                                        KeyStoreData keyStoreData;
                                        KeyStoreManager keyStoreManager;

                                        keyStoreData = new KeyStoreData();
                                        keyStoreData.setupKeyStorePx2();

                                        keyStoreManager = new KeyStoreManager();
                                        keyStore = keyStoreManager.load( keyStoreData );

                                        String HEXCert = keyStoreManager.exportCertificateHEXString ( keyStore, keyStoreData );

                                        selfPeer.setCert( HEXCert );

                                        //***********************************************************************

                                        updatePeerOnAnother( selfPeer, peer.getIp(), "8181" );
                                    }
                                    catch ( PeerException e )
                                    {
                                        Notification.show( "Error accessing remote peer", e.getMessage(),
                                                Notification.Type.ERROR_MESSAGE );
                                    }
                                    break;
                                case REGISTERED:
                                    peer.setStatus( PeerStatus.BLOCKED );
                                    updatePeerOnAnother( peer, peer.getIp(), "8181" );
                                    break;
                                case BLOCKED:
                                    peer.setStatus( PeerStatus.REGISTERED );
                                    updatePeerOnAnother( peer, peer.getIp(), "8181" );
                                    break;
                            }
                            Property property = peersTable.getItem( peer.getId() ).getItemProperty( "Status" );
                            property.setValue( peer.getStatus() );
                            module.getPeerManager().update( peer );
                        }


                        @Override
                        public void OnNegativeButtonTrigger( final PeerInfo peer )
                        {
                            try
                            {
                                PeerInfo selfPeer = getPeerJsonRepresentation( "127.0.0.1", "8181" );
                                switch ( peer.getStatus() )
                                {
                                    case REJECTED:
                                    case APPROVED:
                                    case BLOCKED:
                                    case BLOCKED_PEER:
                                    case REQUEST_SENT:
                                        module.getPeerManager().unregister( peer.getId().toString() );
                                        peersTable.removeItem( peer.getId() );
                                        unregisterPeerFromAnother( selfPeer, peer.getIp(), "8181" );
                                        break;
                                    case REQUESTED:
                                        peer.setStatus( PeerStatus.REJECTED );
                                        module.getPeerManager().update( peer );
                                        Property property =
                                                peersTable.getItem( peer.getId() ).getItemProperty( "Status" );
                                        property.setValue( peer.getStatus() );
                                        selfPeer.setStatus( PeerStatus.BLOCKED_PEER );
                                        updatePeerOnAnother( selfPeer, peer.getIp(), "8181" );
                                        break;
                                }
                            }
                            catch ( PeerException pe )
                            {
                                Notification.show( pe.getMessage(), Notification.Type.ERROR_MESSAGE );
                            }
                        }
                    };
            PeerManageActionsComponent component = new PeerManageActionsComponent( peer, listener );
            peersTable
                    .addItem( new Object[] { peer.getId(), peer.getName(), peer.getIp(), peer.getStatus(), component },
                            peer.getId() );
        }
    }


    private PeerInfo getPeerJsonRepresentation( String ip, String servicePort ) throws PeerException
    {
        String baseUrl = String.format( "http://%s:%s/cxf", ip, servicePort );
        try
        {
            WebClient client = WebClient.create( baseUrl );
            if ( StringUtil.isNumeric( servicePort ) && !Strings.isNullOrEmpty( ip ) )
            {
                client.type( MediaType.MULTIPART_FORM_DATA ).accept( MediaType.APPLICATION_JSON );
                String peerId = client.path( "peer/me" ).get( String.class );
                LOG.warn( peerId );

                if ( !UUIDUtil.isStringAUuid( peerId ) )
                {
                    throw new PeerException( "Failed to obtain peer id" );
                }

                PeerInfo peerInfo = new PeerInfo();
                peerInfo.setId( UUID.fromString( peerId ) );
                peerInfo.setIp( ip );
                peerInfo.setPort( Integer.parseInt( servicePort ) );
                peerInfo.setName( "Peer on " + ip );

                return peerInfo;
            }
            else
            {
                throw new PeerException( "Please supply valid values" );
            }
        }
        catch ( Exception e )
        {
            LOG.error( "PeerRegisterForm@createRegisterButton!clickListener" + e.getMessage(), e );
            throw new PeerException( e );
        }
    }


    private void registerPeerToAnother( PeerInfo peer, String ip, String servicePort )
    {
        String baseUrl = String.format( "http://%s:%s/cxf", ip, servicePort );
        WebClient client = WebClient.create( baseUrl );
        Response response =
                client.path( "peer/register" ).type( MediaType.TEXT_PLAIN ).accept( MediaType.APPLICATION_JSON )
                      .query( "peer", GSON.toJson( peer ) ).post( "" );
        if ( response.getStatus() == Response.Status.OK.getStatusCode() )
        {
            LOG.info( response.toString() );
            Notification.show( String.format( "Request sent to %s!", ip ) );
        }
        else
        {
            LOG.warn( "Response for registering peer: " + response.toString() );
        }
    }


    private void unregisterPeerFromAnother( PeerInfo peer, String ip, String servicePort )
    {
        String baseUrl = String.format( "http://%s:%s/cxf", ip, servicePort );
        WebClient client = WebClient.create( baseUrl );
        Response response =
                client.path( "peer/unregister" ).type( MediaType.TEXT_PLAIN ).accept( MediaType.APPLICATION_JSON )
                      .query( "peerId", GSON.toJson( peer.getId().toString() ) ).delete();
        if ( response.getStatus() == Response.Status.OK.getStatusCode() )
        {
            LOG.info( response.toString() );
            Notification.show( String.format( "Request sent to %s!", ip ) );
        }
        else
        {
            LOG.warn( "Response for registering peer: " + response.toString() );
        }
    }


    private void updatePeerOnAnother( PeerInfo peer, String ip, String servicePort )
    {
        String baseUrl = String.format( "http://%s:%s/cxf", ip, servicePort );
        WebClient client = WebClient.create( baseUrl );
        Response response =
                client.path( "peer/update" ).type( MediaType.TEXT_PLAIN ).accept( MediaType.APPLICATION_JSON )
                      .query( "peer", GSON.toJson( peer ) ).put( "" );
        if ( response.getStatus() == Response.Status.OK.getStatusCode() )
        {
            LOG.info( response.toString() );
            Notification.show( String.format( "Request sent to %s!", ip ) );
        }
        else
        {
            LOG.warn( "Response for registering peer: " + response.toString() );
        }
    }


    private Button createRegisterButton()
    {
        registerRequestButton = new Button();
        registerRequestButton.setCaption( "Register" );
        registerRequestButton.setImmediate( true );
        registerRequestButton.setWidth( "-1px" );
        registerRequestButton.setHeight( "-1px" );

        registerRequestButton.addClickListener( new Button.ClickListener()
        {
            @Override
            public void buttonClick( final Button.ClickEvent clickEvent )
            {
                getUI().access( new Runnable()
                {
                    @Override
                    public void run()
                    {
                        String servicePort = servicePortTextField.getValue();
                        String ip = ipTextField.getValue();
                        LOG.warn( ip );

                        try
                        {
                            PeerInfo remotePeer = getPeerJsonRepresentation( ip, servicePort );
                            remotePeer.setStatus( PeerStatus.REQUEST_SENT );
                            module.getPeerManager().register( remotePeer );
                            PeerInfo selfPeer = getPeerJsonRepresentation( "127.0.0.1", servicePort );
                            selfPeer.setStatus( PeerStatus.REQUESTED );

                            registerPeerToAnother( selfPeer, ip, servicePort );

                            showPeersButton.click();
                        }
                        catch ( PeerException e )
                        {
                            Notification.show( e.getMessage(), Notification.Type.ERROR_MESSAGE );
                        }
                    }
                } );
            }
        } );

        return registerRequestButton;
    }
}