#!/bin/sh
set -e 
pig="pig-0.12.0"

# Remove Pig Files and Folders
if [ -d "/opt/$pig" ]; then
	rm -r /opt/$pig
fi

if [ -f "/etc/profile.d/pig-home.sh" ]; then
	rm /etc/profile.d/pig-home.sh
fi

FilePath="/etc/profile"
. $FilePath
