#!/bin/bash 
set -e 
pigVersion="pig-0.13.0"

# Remove Pig Files and Folders
if [ -d "/opt/$pigVersion" ]; then
	rm -r /opt/$pigVersion
fi

if [ -f "/etc/profile.d/pig-home.sh" ]; then
	rm /etc/profile.d/pig-home.sh
fi

FilePath="/etc/profile"
. $FilePath