#!/bin/bash 
set -e 
pigVersion="pig-0.13.0"
pigBin="/usr/local/bin"

# Remove any symlinks that are broken under /usr/local/bin directory
find -L $pigBin -maxdepth 1 -type l -delete

# Remove Pig Files and Folders
if [ -d "/opt/$pigVersion" ]; then
	rm -r /opt/$pigVersion
fi

if [ -f "/etc/profile.d/pig-home.sh" ]; then
	rm /etc/profile.d/pig-home.sh
fi

FilePath="/etc/profile"
. $FilePath