#!/bin/bash 
set -e
pigVersion="pig-0.13.0"
FilePath="/etc/profile"

. $FilePath

pigHome="/opt/$pigVersion"
pigConf="/etc/pig"

if [[ "x$PIG_HOME" != "x" ]];
then
        pigHome=$PIG_HOME
fi

if [[ "x$PIG_CONF_DIR" != "x" ]];
then
        pigConf=$PIG_CONF_DIR
fi


# Create symlink to configuration files and scripts
ln -sf $pigConf/* $pigHome/conf/
ln -sf $pigHome/bin/* /usr/local/bin/
