#!/bin/bash
set -e
sharkVer="shark-0.9.1"

FilePath="/etc/profile"
. $FilePath

sharkVer="spark-0.9.1"
sharkHome="/opt/$sharkVer"
sharkConf="/etc/shark"

if [[ "x$SHARK_HOME" != "x" ]];
then
        sharkHome=$SHARK_HOME
fi

# Create symlink to configuration files
ln -sf $sharkConf/* $sharkHome/conf/
