#!/bin/bash
set -e
sharkVer="shark-0.9.1"

#Remove paths and exports from relevant files
FilePath="/etc/profile"

# Remove Shark Files and Folders
if [ -d "/opt/$sharkVer" ]; then
	rm -r /opt/$sharkVer
fi

if [ -f "/etc/profile.d/shark-home.sh" ]; then
	rm /etc/profile.d/shark-home.sh
fi

. $FilePath
