#!/bin/bash
pigVersion="pig-0.13.0"
. /etc/profile

pigHome="/opt/$pigVersion"
pigConf="/etc/pig"

if [[ "x$PIG_HOME" != "x" ]];
then
        pigHome=$PIG_HOME
fi

if [[ "x$PIG_CONF_DIR" != "x" ]];
then
        pigConf=$PIG_CONF_DIR
fi

. $pigConf/pig-env.sh


case "$1" in
start)
	echo "Starting PIG ..."
	cd $pigHome/bin
	./pig
;;

stop)
	echo "Stopping PIG ..."
        kill `ps aux | grep D[p]ig.home.dir=/opt/$pig | awk '{print $2}'`
;;

restart)
        $0 stop
        $0 start
;;

status)
	line1=$(ps aux | grep D[p]ig.home.dir=/opt/$pig)
       
        #Check if the output is empty or not
        if [ -n "$line1" ]; then
                echo "PIG is Running"
                exit 0
        else
                echo "PIG is NOT Running"
                #exit 1
        fi
;;

*)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

