#!/bin/bash 
set -e
# Remove Hipi Files and Folders
if [ -d "/opt/hipi" ]; then
	rm -r /opt/hipi
fi

# Remove paths and exports from relevant files
FilePath="/etc/profile"

if [ -f "/etc/profile.d/hipi-home.sh" ]; then
        rm -r /etc/profile.d/hipi-home.sh
fi

. $FilePath
