#!/bin/bash
function generate_hex_pair {
printf '%x%x' "`shuf -i 0-15 -n 1`" "`shuf -i 0-15 -n 1`"
}

function create_mac {
local RANGE=255
local a="`generate_hex_pair`"
local b="`generate_hex_pair`"
local c="`generate_hex_pair`"
local prefix="00:16:3c"
echo "${prefix}:${a}:${b}:${c}"
}

lxc_name="$1"
lxc_home="$HOME/.local/share/lxc/$lxc_name"
lxc_config="$lxc_home/config"
ovs_bridge="br-int"
lxc_mac="`create_mac`"
lxc_ip="`cat $lxc_config | grep lxc.network.ipv4 | awk '{print $3}'`"
vlan_id="`cat $lxc_config | grep lxc.network.vlan.id | awk '{print $3}'`"
cat $lxc_config | grep lxc.network.hwaddr > /dev/null 2>&1
if [ $? != 0 ]; then
  echo "#lxc.network.hwaddr = $lxc_mac" | sudo tee -a $lxc_config > /dev/null
  port_name="`echo "${lxc_mac//:}"`-1"
else
  lxc_mac="`cat $lxc_config | grep lxc.network.hwaddr | awk '{print $3}'`"
  port_name="`echo "${lxc_mac//:}"`-1"
fi


lxc_pid="`lxc-info -n $lxc_name | grep PID: | awk '{print $2}'`"
sudo ovs-vsctl del-port $port_name  > /dev/null 2>&1
sudo ovs-vsctl add-port $ovs_bridge $port_name tag=$vlan_id
sudo ovs-vsctl set interface $port_name type=internal
sudo ip link set $port_name netns $lxc_pid
lxc-attach -n $lxc_name -- ifconfig $port_name $lxc_ip

