#!/bin/bash
# Starts and stops Oozie Client.

case "$1" in
start)
	start-stop-daemon --start --exec /opt/oozie-client-3.3.2/bin/oozie
;;

stop)
	start-stop-daemon --stop --exec /opt/oozie-3.3.2/bin/oozie
;;

restart)
	$0 stop
	$0 start
;;

status)
	line=$(ps aux | grep [o]oozie-client)
	if [ -n "$line" ]; then
		echo "Oozie Client is Running"
		exit 0
	else
		echo "Oozie Client is NOT Running"
		exit 1
	fi
;;

*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac
