#!/bin/sh
# Starts and stops hive CLI.

case "$1" in
start)
        start-stop-daemon --start --exec /opt/hive-0.11.0-bin/bin/hive
;;

stop)
	line=$(ps aux | grep [h]ive-0.11.0-bin/lib/)
	
	if [ -n "$line" ]; then
		kill `ps aux | grep [h]ive | awk '{print $2}'`
		exit 0
        else
                echo "Hive CLI is NOT Running"
                exit 1
        fi
;;

restart)
        $0 stop
        $0 start
;;

status)
        line=$(ps aux | grep [h]ive-0.11.0-bin/lib/)
        if [ -n "$line" ]; then
                echo "Hive CLI is Running"
                exit 0
        else
                echo "Hive CLI is NOT Running"
                exit 1
        fi
;;

*)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac
