#!/bin/bash
set -e
sudo update-rc.d subutai-management start 22 2 3 4 5 . stop 15 0 6 .

FilePath="/etc/profile"
subutaiHomeEcho="/opt/subutai-management"

if grep -q "export SUBUTAI_MANAGEMENT_HOME=" $FilePath
then
        echo "subutai home is already added!"
else
        echo "subutai home is being inserted"
        echo "export SUBUTAI_MANAGEMENT_HOME="$subutaiHomeEcho >> $FilePath
fi
. $FilePath
