#!/bin/bash

# Exit on error
set -e
. /etc/profile

if [ "x$HIVE_HOME" = "x" ];
then
	HIVE_HOME=/opt/hive
fi

if [ -d "$HIVE_HOME" ]; then
        echo "$HIVE_HOME exists!"
	rm -r $HIVE_HOME
else
        echo "$HIVE_HOME does not exist!"
fi

if [ -f "/etc/init.d/hive" ]; then
        rm  /etc/init.d/hive
fi
if [ -f "/etc/init.d/hive-thrift" ]; then
        rm  /etc/init.d/hive-thrift
fi
if [ -d "/etc/hive" ]; then
        rm -r /etc/hive
fi
