#!/bin/bash

# Exit on error
set -e

. /etc/profile

if [ "x$HIVE_HOME" = "x" ];
then
       	HIVE_HOME="/opt/hive"
fi
hiveConf="/etc/hive"

ln -sf $hiveConf/* $hiveHome/conf/
# Make symlink files read-only
chmod 444 -R $hiveHome/conf/
