#!/bin/bash

# Exit on error
set -e

. /etc/profile

if [ "x$HIVE_HOME" = "x" ];
then
       	HIVE_HOME="/opt/hive"
fi
hiveConf="/etc/hive"
hiveBin="/usr/local/bin"
hiveHomeBin="$HIVE_HOME/bin"
mkdir -p $hiveBin

ln -sf $hiveConf/* $hiveHome/conf/
ln -sf $hiveHomeBin/* $hiveBin/
