#!/bin/sh
# Starts and stops hive thrift server.

ACTIVEMQ_HOME="/opt/apache-activemq-5.9.1"
ACTIVEMQ_BIN=$ACTIVEMQ_HOME"/bin/"
ACTIVEMQ_DATA="/opt/apache-activemq-5.9.1/data"
hostname=$(hostname)
ACTIVEMQ_PIDFILE="$ACTIVEMQ_DATA/activemq-`hostname`.pid"

case "$1" in
start)
        if [ -f $ACTIVEMQ_PIDFILE ];
        then
                echo "Apache Activemq is already running.."
        else
		sudo $ACTIVEMQ_BIN/activemq start
                echo "Apache Activemq is starting.."
        fi

;;
stop)

        if [ -f $ACTIVEMQ_PIDFILE ];
        then
		echo "Apache Activemq is stopping now.."
		sudo $ACTIVEMQ_BIN/activemq stop
        else
                echo "Apache Activemq is not running now.."
        fi
        ;;
restart)
	sudo $ACTIVEMQ_BIN/activemq restart
        ;;
status)
	sudo $ACTIVEMQ_BIN/activemq status
        ;;
esac

