#!/bin/sh
# Starts and stops hive thrift server.

ACTIVEMQ_HOME="/opt/apache-activemq-5.9.1"
ACTIVEMQ_BIN=$ACTIVEMQ_HOME"/bin/"
ACTIVEMQ_DATA="/opt/apache-activemq-5.9.1/data"
hostname=$(hostname)
ACTIVEMQ_PIDFILE="$ACTIVEMQ_DATA/activemq-`hostname`.pid"

case "$1" in
start)
        if [ -f $ACTIVEMQ_PIDFILE ];
        then
                echo "Apache Activemq is already running.."
        else
		$ACTIVEMQ_BIN/activemq start
                echo "Apache Activemq is starting.."
        fi

;;
stop)

        if [ -f $ACTIVEMQ_PIDFILE ];
        then
		$ACTIVEMQ_BIN/activemq stop
                echo "Apache Activemq is stopping now.."
                rm $ACTIVEMQ_PIDFILE
        else
                echo "Apache Activemq is not running now.."
        fi
        ;;
restart)
	$ACTIVEMQ_BIN/activemq restart
        ;;
status)

        if [ -f $ACTIVEMQ_PIDFILE ];
        then
		$ACTIVEMQ_BIN/activemq status
        else
                echo "Apache Activemq is not running now.."
        fi
        ;;

esac

