#!/bin/bash

# Exit on error
set -e

hadoopBin="/usr/local/bin"
# Remove any symlinks that are broken under hadoop bin directory
find -L $hadoopBin -maxdepth 1 -type l -delete

# Remove Hadoop Files and Folders
if [ -d "/opt/hadoop-1.2.1" ]; then
	rm -r /opt/hadoop-1.2.1
fi

if ls /var/lib/*hadoop* ; then
        rm -r /var/lib/*hadoop*
fi

if [ -d "/etc/hadoop" ]; then
        rm -r /etc/hadoop
fi

if [ -f "/etc/init.d/hadoop-dfs" ]; then
	rm  /etc/init.d/hadoop-dfs
fi

if [ -f "/etc/init.d/hadoop-mapred" ]; then
        rm  /etc/init.d/hadoop-mapred
fi

if [ -f "/etc/init.d/hadoop-all" ]; then
        rm  /etc/init.d/hadoop-all
fi
