#!/bin/bash

# Exit on error
set -e

hadoopHome=/opt/hadoop-1.2.1
if [[ "x$HADOOP_HOME" != "x" ]];
then
        hadoopHome=$HADOOP_HOME
fi

# Remove Hadoop Files and Folders
if [ -d $hadoopHome ]; then
	rm -r $hadoopHome
fi

if ls /var/lib/*hadoop* ; then
        rm -r /var/lib/*hadoop*
fi

if [ -d "/etc/hadoop" ]; then
        rm -r /etc/hadoop
fi

if [ -f "/etc/init.d/hadoop-dfs" ]; then
	rm  /etc/init.d/hadoop-dfs
fi

if [ -f "/etc/init.d/hadoop-mapred" ]; then
        rm  /etc/init.d/hadoop-mapred
fi

if [ -f "/etc/init.d/hadoop-all" ]; then
        rm  /etc/init.d/hadoop-all
fi
