#!/bin/sh

# Exit on error
set -e

. /etc/profile
# Remove zookeeper related folders
if [ -d "/var/zookeeper" ]; then
        echo "/var/zookeeper exists!"
        rm -r /var/zookeeper
else
        echo "/var/zookeeper does not exist!"
fi
