#!/bin/bash
set -e

. /etc/profile

zookeeperHome="/opt/zookeeper-3.4.5"
zookeeperConf="/etc/zookeeper"

if [[ "x$ZOOKEEPER_HOME" != "x" ]];
then
        zookeeperHome=$ZOOKEEPER_HOME
fi

if [[ "x$ZOOKEEPER_CONF_DIR" != "x" ]];
then
        zookeeperConf=$ZOOKEEPER_CONF_DIR
fi

# Create symlink to configuration files
ln -sf $zookeeperConf/* $zookeeperHome/conf/
