#!/bin/sh

tar -xpzf /opt/zookeeper-3.4.5.tar.gz -C /opt
rm -rf /opt/zookeeper-3.4.5.tar.gz

# Create zookeeper related folders into "/var" directory
if [ -d "/var/zookeeper" ]; then
        echo "/var/zookeeper exists!"
else
        echo "/var/zookeeper does not exist!"
	mkdir /var/zookeeper
fi

FilePath="/etc/profile"
zookeeperHomeEcho="/opt/zookeeper-3.4.5"
zookeeperPath="\/opt\/zookeeper-3.4.5\/bin"
zookeeperPathEcho=$zookeeperHomeEcho"/bin"

# edit zkServer.sh script to clean warning "[: /var/zookeeper/: unexpected operator"
sed -i "s/if \[ \-f \$ZOOPIDFILE \]; then/    if [ -f \"\$ZOOPIDFILE\" ]; then/g" $zookeeperHomeEcho/bin/zkServer.sh
. $FilePath
