package org.safehaus.subutai.core.peer.impl;


public enum RecipientType
{
    COMMAND_REQUEST, COMMAND_RESPONSE, CONTAINER_CREATE_REQUEST, CONTAINER_CREATE_RESPONSE, PEER_REQUEST_LISTENER,
    PEER_RESPONSE_LISTENER, ECHO_LISTENER
}
