#!/bin/sh

# Exit on error
set -e
. /etc/profile
if [ "x$OOZIE_CLIENT_HOME" = "x" ];
then
        OOZIE_CLIENT_HOME=/opt/oozie-client-3.3.2
fi
# Remove Oozie Files and Folders
if [ -d $OOZIE_CLIENT_HOME ]; then
        rm -r $OOZIE_CLIENT_HOME
fi
