#!/bin/sh

# Exit on error
set -e

. /etc/profile
if [[ "x$OOZIE_CLIENT_HOME" == "x" ]];
then
	OOZIE_CLIENT_HOME=/opt/oozie-client-3.3.2
fi
# Remove Oozie Files and Folders
if [ -d $OOZIE_CLIENT_HOME ]; then
	echo $OOZIE_CLIENT_HOME "exists!"
	rm -r $OOZIE_CLIENT_HOME
else
	echo $OOZIE_CLIENT_HOME "does not exist!"
fi
