#!/bin/sh

# Exit on error
set -e

# Remove Oozie Files and Folders
if [ -d "/opt/oozie-client-3.3.2" ]; then
        echo "/opt/oozie-client-3.3.2 exists!"
	rm -r /opt/oozie-client-3.3.2
else
        echo "/opt/oozie-client-3.3.2 does not exist!"
fi

#Remove paths and exports from relevant files
FilePath="/etc/profile"
OozieClientHome="\/opt\/oozie-client-3.3.2"
OozieClientPath="\/opt\/oozie-client-3.3.2\/bin"

if grep -q "OOZIE_CLIENT_HOME=" $FilePath
then
        echo "oozie client home is being deleted!"
        sed -i "/OOZIE_CLIENT_HOME=$OozieClientHome/d" $FilePath
else
        echo "oozie client home does not exist"
fi

if grep -q "export PATH=" $FilePath
then
        echo "Path is previously insterted to" $FilePath
        if grep -q "${OozieClientPath}" $FilePath
        then
                echo "Oozie Client path is being deleted from path!"
                sed -i "s/$OozieClientPath://g" $FilePath
                sed -i "s/:$OozieClientPath//g" $FilePath
        else
                echo "Oozie client path does not exist on path"
        fi
else
        echo "PATH does not exist"
fi

if [ -f "/etc/init.d/oozie-client" ]; then
        rm  /etc/init.d/oozie-client
fi
. $FilePath
