#!/bin/bash

function print_usage() {
cat <<EOF
subutai-run - execute command with autopiping output to specified files
Usage: subutai-run PROGRAM OUTPUT

PROGRAM     - specify a command to run
OUTPUT      - name an output file. Notice, that _out appendix will be added to
stdout of a PROGRAM and _err to a STDERR.
EOF
}

if [[ $# -eq 0 || $# -eq 1 ]]; then
    print_usage
    exit 1
fi

COMMAND=
LAST_ARG=${!#}

for var in $@
do
    if [ $var == $LAST_ARG ]; then
        echo "Finished accepting arguments"
    else
        COMMAND="$COMMAND $var"
    fi
done

$COMMAND 1> /tmp/${LAST_ARG}_out 2> /tmp/${LAST_ARG}_err &
exit $?
