#!/bin/bash



function clone_usage {
  echo -----------------------------------------------------------------------
  echo Usage: Clone a new container instance from a temlate.
  echo
  echo "        "subutai \[-qh\] clone parent child
  echo
  echo -----------------------------------------------------------------------
}


function clone {
  if [ "`is_system_locked`" == "true" ]
  then
     msg_error "System locked by a subutai process"
     exit 1
  fi

  local parent="$1"
  local child="$2"
  config=/var/lib/lxc/$child/config
  if [ "`are_containers_readable $parent $child`" == "true" ]
  then
     msg_error "Container(s) locked by a subutai process"
     exit 1
  fi

  if [ -z "$parent" ]; then
    msg_error "Parameters not provided. Aborting ..."
    show_usage "`usage`"
  fi

  if [ -z "$child" ]; then
    msg_error "Child parameter not provided. Aborting ..."
    show_usage "`usage`"
  fi
  
  OPTIND=0
  if [ "$2" == $child ]; then
    shift
    shift
  fi
  #getting environmentId using getopts
  local environmentId=""
  local ovs_enabled="false"
  shift_amount=0;
  while getopts ":e:" opt; do
     case $opt in
       e)
          environmentId=$OPTARG;
          ;;
       o)
	  ovs_enabled="true"
	  ;;
       \?)
          msg_error "Unrecognized option -$OPTARG"
          exit 1
          ;;
     esac
     shift_amount=$(($shift_amount + 1))
  done
   
  lock_container_write $parent $child
  if [ $? != 0 ]; then msg_error "Containers cannot be locked!"; exit 1; fi
  
  # NOTE: underscore for our own lxc clone impl not supplied lxc-clone
  if [ -z "$environmentId" ]; then
     environmentId="null"
  fi
  
  #cloning operation is starting..
  lxc_clone $parent $child $environmentId "`usage`"
  
  # Create 2 veth for container if openvswitch is enabled
  if [ "x$ovs_enabled" == "xtrue" ]; then
    msg_info "    - configuring $child network with openvswitch"
    ovs_configure_lxc $child
  fi

  git_child_branch $child
  msg_ok "Successfully cloned $child container from $parent"
  unlock_container_write $child
  if [ $? != 0 ]; then msg_error "Container(s) cannot be unlocked!"; exit 1; fi
}


function clone_description {
  echo clones an instance container from a template
}

