#!/bin/bash


function demote_usage {
  echo -----------------------------------------------------------------------
  echo Usage: Demotes a temlate back into a container instance.
  echo
  echo "        "subutai \[-qh\] demote template
  echo
  echo -----------------------------------------------------------------------
}


function demote {
  local temp="$1"

  #check for master	
  if [ $temp == "master" ]; then
    msg_error "Master templated cannot be demoted. Aborting ..."
    exit 1
  fi

  # check to make sure we have a template name - usage if not
  if [ -z "$temp" ]; then
    msg_error "Template argument not provided. Aborting ..."
    show_usage "`demote_usage`"
  fi

  # various sanity checks: lxc exists, it's a template, no kids, not registered
  lxc_assert "$temp"
  if [ "false" == "`zfs_is_template $temp`" ]; then
    msg_error "Supplied template name \"$temp\" is not a template. Aborting ..."
    exit 1
  fi

  zfs_get_children "$temp"
  local child_count="$?"
  if [ "$child_count" -gt 0 ]; then
    msg_error "Template \"$temp\" cannot be demoted with $child_count children."
    exit 1
  elif [ "true" == "`is_registered $temp`" ]; then
    msg_error "Cannot demote registered template \"$temp\""
    exit 1
  else
    msg_info "Demoting template \"$temp\" with no children."
  fi

  # actual code to demote the template here
  local lxc_path="/var/lib/lxc/$temp"
  cat $lxc_path/config | \
    grep -v "lxc.hook.pre-start" | \
    grep -v "subutai.template.package" | \
    grep -v "subutai.git.uuid" >> $lxc_path/config.new
  rm $lxc_path/config
  mv $lxc_path/config.new $lxc_path/config
 
  local var_snap="lxc-data/$temp-var@template"
  zfs release keep "$var_snap"
  zfs destroy "$var_snap"
  zfs set readonly=off "lxc-data/$temp-var"

  local home_snap="lxc-data/$temp-home@template"
  zfs release keep "$home_snap"
  zfs destroy "$home_snap"
  zfs set readonly=off "lxc-data/$temp-home"

  local opt_snap="lxc/$temp-opt@template"
  zfs release keep "$opt_snap"
  zfs destroy "$opt_snap"
  zfs set readonly=off "lxc/$temp-opt"

  local root_snap="lxc/$temp@template"
  zfs release keep "$root_snap"
  zfs destroy "$root_snap"
  zfs set readonly=off "lxc/$temp"
}


function demote_description {
  echo demotes a template back to an instance container
}

