#!/bin/bash


function export_usage {
  echo -----------------------------------------------------------------------
  echo Usage: Exports a template as a debian pkg
  echo
  echo "        "subutai export template \[-v version\]
  echo
  echo -----------------------------------------------------------------------
}


# Plan for exporting a template
# -----------------------------------------------------------------------------
# (1) perform sanity checks first
#     - given version should be valid 
#     - defer exports of master to the subutai-master-export script
#     - template container MUST exist
#     - container MUST be a template with the '@template' snapshot
#     - container parent MUST be present in the template registry
# (2) generate delta images of all filesystems: 
#     'pool/parent-partition@child' -> 'pool/child-partition@template'
# (3) generate the debian file deltas, and package info

function export {
  if [ "`is_system_locked`" == "true" ]
  then
     msg_error "System locked by a subutai process"
     exit 1
  fi

  OPTIND=0
  local container="$1"
  lxc_assert "$container" "`usage`"

  if [ "$container" == "master" ]; then
    echo "Please use master_export command!"
    unlock_container_write $container
    if [ $? != 0 ]; then msg_error "Container(s) cannot be unlocked!"; exit 1; fi
    exit 1
  fi

  shift
  while getopts ":v:" opt; do
    case $opt in
      v)
        version="$OPTARG"
        ;;
      \?)
        msg_error "Unrecognized option -$OPTARG"
        exit 1
        ;;
      :)
        msg_error "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
    esac
  done

  if [ -z $version ];then
    version=$SUBUTAI_VERSION
  fi
  
  assert_version_validity $version
   
  ps aux | grep "[s]ubutai export $container$" | grep -v $$ > /dev/null 2>&1
  local stat=$?
  if [ "$stat" == "0" ]
  then
    msg_error "Container \"$container\" is being exported by other process!"
    exit 1
  fi

  if [ "`are_containers_readable $container`" == "true" ]
  then
     msg_error "Container(s) locked by a subutai process"
     exit 1
  fi

  lock_container_write $container
  if [ $? != 0 ]; then msg_error "Containers cannot be locked!"; exit 1; fi

  # ----------------------------------------------------------------------------
  # (1) perform some sanity checks
  # ----------------------------------------------------------------------------

  lxc_assert $container "`export_usage`"

  if [ "$container" == "master" ]; then
    echo "Please use master_export command!"
    unlock_container_write $container
    if [ $? != 0 ]; then msg_error "Container(s) cannot be unlocked!"; exit 1; fi
    exit 1
  fi

  local debian_package_name=`get_debian_package_name $container $version` 
  local debian_file="$SUBUTAI_TMPDIR/$debian_package_name.deb"

  if [ -f $debian_file ]; then
    msg_error "It seems the debian file has already been generated for this version: $version"
    msg_error "Destroy $SUBUTAI_TMPDIR/$container and the peer debian file first"
    unlock_container_write $container
    if [ $? != 0 ]; then msg_error "Container(s) cannot be unlocked!"; exit 1; fi
    exit 1
  fi

  # check to make sure the container is a template
  if [ "`fs_is_template $container`" == "false" ]; then
    msg_error "Container \"$container\" is NOT a template. Aborting ..."
    unlock_container_write $container
    if [ $? != 0 ]; then msg_error "Container(s) cannot be unlocked!"; exit 1; fi
    exit 1
  else
    msg_info "    - check passed: \"$container\" is a template"
  fi

  parent=`fs_get_parent $container`
  lxc_assert $parent
  # check to make sure the parent is a template
  if [ "`fs_is_template $parent`" == "false" ]; then
    msg_error "Parent \"$parent\" is NOT a template. Aborting ..."
    unlock_container_write $container
    if [ $? != 0 ]; then msg_error "Container(s) cannot be unlocked!"; exit 1; fi
    exit 1
  else
    msg_info "    - check passed: parent \"$parent\" is a template"
  fi

  # check to make sure the parent is registered
  if [ "`is_registered $parent`" == "false" ]; then
    msg_error "Parent \"$parent\" is NOT registered. Aborting ..."
    unlock_container_write $container
    if [ $? != 0 ]; then msg_error "Container(s) cannot be unlocked!"; exit 1; fi
    exit 1
  else
    msg_info "    - check passed: parent \"$parent\" is registered"
  fi

  # ----------------------------------------------------------------------------
  # (2) generate delta images of all filesystems: 
  #     'pool/parent-partition@child' -> 'pool/child-partition@template'
  # ----------------------------------------------------------------------------

  debian_dir=$SUBUTAI_TMPDIR/$debian_package_name
  debian_root="$debian_dir$SUBUTAI_TMPDIR/$container"
  deltas="$debian_root/deltas"
  mkdir -p $deltas
  fs_send $parent $container $deltas

  # ----------------------------------------------------------------------------
  # (3) generate the debian file from deltas, and package info
  # ----------------------------------------------------------------------------
  
  # insert subutai.template.package info inside containers config file
  local conf="/var/lib/lxc/$container/config"
  local propline="`cat $conf | grep subutai.template.package`"

  if [ -z "$propline" ]; then
    echo "subutai.template.package = $debian_dir.deb" >> /var/lib/lxc/$container/config
    debian_file=$debian_dir".deb"
  else
    escaped_debian_dir=$(echo $debian_dir | sed -e 's/\//\\\//g')
    sed -i "s/subutai.template.package = *.*/subutai.template.package = $escaped_debian_dir.deb/g" $conf 
    debian_file=$debian_dir".deb"
  fi
  local version_variable="subutai.template.version"
  local version_propline="`cat $conf | grep $version_variable`"

  if [ -z "$version_propline" ]; then
    echo "$version_variable = $version" >> /var/lib/lxc/$container/config
  else
    sed -i "s/$version_variable = *.*/$version_variable = $version/g" $conf 
  fi

  cp /var/lib/lxc/$container/config $debian_root
  cp /var/lib/lxc/$container/fstab  $debian_root
  cp /var/lib/lxc/$container/packages  $debian_root
  cp -a /var/lib/lxc/$container/rootfs/.git $debian_root/

  pkg=`deb_pkg $container $version`
  check_status "debian package $pkg generated" "$?"
  
  # Remove debian directory after debian package generation
  rm -rf $debian_dir
  unlock_container_write $container
}


function export_description {
  echo export a template
}
