#!/bin/bash


function unregister_usage {
  echo -----------------------------------------------------------------------
  echo Usage: Unregisters the template debian pkg from the site template registry
  echo
  echo "        "subutai unregister template
  echo
  echo -----------------------------------------------------------------------
}


# Plan for unregistering a template
# -----------------------------------------------------------------------------
# (1) perform sanity checks first
#     - master cannot be unregistered
#     - template shoud have been registered
#     - template should not have child templates registered
#     - template should not be being used by other FAI machines
# (2) Unregister the template

function unregister {
  if [ "`is_system_locked`" == "true" ]
  then
     msg_error "System locked by a subutai process"
     exit 1
  fi

  local template="$1"

  # ----------------------------------------------------------------------------
  # (1) perform some sanity checks
  # ----------------------------------------------------------------------------
 
  if [ $template == "master" ]; then
    msg_error "master template cannot be unregistered"
    exit 1
  fi

  if [ "`are_containers_locked_write $template`" == "true" ]
  then
    msg_error "Template $template is being used by a subutai process"
    exit 1
  fi

  lock_container_write $template
  if [ $? != 0 ]; then 
    msg_error "Template $template cannot be locked!"
    exit 1
  fi

  # check to make sure container is registered as a template
  if [ "`is_registered $template`" == "false" ]; then
    msg_error "Template \"$template\" is NOT registered. Aborting ..."
    unlock_container_write $container
    if [ $? != 0 ]; then 
      msg_error "Container(s) cannot be unlocked!"
      exit 1
    fi
    exit 1
  else
    msg_info "    - check passed: \"$template\" is registered"
  fi

  parent=`zfs_get_parent $template`

  # check to make sure the parent is registered if container itself is not master
  if [ $template != "master" -a "`is_registered $parent`" == "false" ]; then
    msg_error "Parent \"$parent\" is NOT registered. Aborting ..."
    unlock_container_write $template
    if [ $? != 0 ]; then msg_error "Template \"$template\" cannot be unlocked!"
      exit 1 
    fi
    exit 1
  elif [ $template != "master" ]; then
    msg_info "    - check passed: parent \"$parent\" is registered"
  fi

  # check to make sure no child templates registered
  if [ "`has_child_templates_registered $template`" == "true" ]; then
    msg_error "There are child templates registered of template \"$template\". Aborting ..."
    unlock_container_write $container
    if [ $? != 0 ]; then
      msg_error "Container(s) cannot be unlocked!"
      exit 1
    fi
    exit 1
  else
    msg_info "    - check passed: no child templates of \"$template\" registered"
  fi

  # check to make sure template is not being used by other FAI machines
  if [ "`is_template_in_use $template`" == "true" ]; then
    msg_error "Template \"$template\" is in use. Aborting ..."
    unlock_container_write $container
    if [ $? != 0 ]; then
      msg_error "Container(s) cannot be unlocked!"
      exit 1
    fi
    exit 1
  else
    msg_info "    - check passed: \"$template\" is not in use"
  fi

  # ----------------------------------------------------------------------------
  # (2) Unregister the template
  # ----------------------------------------------------------------------------
  
  delete_n_unregister $template 

  unlock_container_write $template
  if [ $? != 0 ]; then 
    msg_error "Template $template cannot be unlocked!"
    exit 1
  fi
}


function unregister_description {
  echo unregisters the template from the site registry
}


