#!/bin/bash
# Presto-Server

prestoVer="0.61"
presto="presto-server-$prestoVer"

. /etc/profile

case "$1" in
start)
	echo "Starting Presto Instance ..."
	cd /opt/$presto/bin
	./launcher start
;;

stop)
	echo "Stoping Presto Instance ..."
	cd /opt/$presto/bin
	./launcher stop
;;

restart)
        $0 stop
        $0 start
;;

status)
	cd /opt/$presto/bin
	./launcher status
;;

*)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

