#!/bin/bash
# Presto

prestoVer="0.69"
presto="presto-server-$prestoVer"

. /etc/profile

if [ "$#" != 3 ]; then
    	echo "Usage: $0 {start|stop|restart} 'presto-server' 'catalog'"
		echo "Available catalogs : hive, jmx, cassandra"
	exit
fi

host=$2
catalog=$3

case "$1" in
start)
	echo "Starting Presto Client ..."
	cd /opt/$presto
	ping -c 1 -w 5 $host &>/dev/null
	if [ $? -ne 0 ] ; then
		echo "Presto Server unreachable !!!"
		exit
	else
		java -jar presto-cli-$prestoVer-executable.jar --server $host:8413 --catalog $catalog --schema default
	fi
;;

stop)
	echo "Stoping Presto Client ..."
	cd /opt/$presto
	kill `ps aux | grep [p]resto-cli-$prestoVer-executable.jar | awk '{print $2}'`
;;

restart)
	$0 stop
	$0 start
;;

*)
	echo "Usage: $0 {start|stop|restart} $1 'presto-server' 'catalog'"
	echo "Available catalogs : hive, jmx, cassandra"
	exit
esac
