#!/bin/bash

# Exit on error
set -e
. /etc/profile

if [ "x$OOZIE_SERVER_HOME" = "x" ];
then
	OOZIE_SERVER_HOME=/opt/oozie-3.3.2
fi
# Remove Oozie Files and Folders
if [ -d $OOZIE_SERVER_HOME ]; then
        rm -r $OOZIE_SERVER_HOME
fi
