#!/bin/sh

# Exit on error
set -e

tar -xpzf /opt/oozie-3.3.2-distro.tar.gz -C /opt
rm -rf /opt/oozie-3.3.2-distro.tar.gz
tar -xpzf /opt/libext.tar.gz -C /opt/oozie-3.3.2
rm -rf /opt/libext.tar.gz
tar -xpzf /opt/ext-2.2.tar.gz -C /opt/oozie-3.3.2
rm -rf /opt/ext-2.2.tar.gz

oozieHomeEcho="/opt/oozie-3.3.2"

cd /opt  
$oozieHomeEcho/bin/oozie-setup.sh -extjs $oozieHomeEcho/ext-2.2
$oozieHomeEcho/bin/ooziedb.sh create -sqlfile oozie.sql -run
