#!/bin/bash

# Exit on error
set -e

. /etc/profile

if [ "x$OOZIE_SERVER_HOME" = "x" ];
then
        OOZIE_SERVER_HOME=/opt/oozie-3.3.2
fi

pushd /opt
$OOZIE_SERVER_HOME/bin/oozie-setup.sh -extjs $OOZIE_SERVER_HOME/ext-2.2
$OOZIE_SERVER_HOME/bin/ooziedb.sh create -sqlfile oozie.sql -run
if [ -f "oozie.sql" ]; then
    rm oozie.sql
fi
popd
