package org.safehaus.subutai.core.shiro.ui.tabs;


import org.safehaus.subutai.common.protocol.Disposable;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DefaultFieldFactory;
import com.vaadin.ui.Field;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Runo;


/**
 * Created by talas on 1/21/15.
 */
public class RoleManagementForm extends CustomComponent implements Disposable
{
    //Permissions
    //Roles associated with permissions

    private PermissionsTab permissionsTab;
    private RolesTab rolesTab;


    public RoleManagementForm()
    {
        TabSheet sheet = new TabSheet();
        sheet.setStyleName( Runo.TABSHEET_SMALL );
        sheet.setSizeFull();

        permissionsTab = new PermissionsTab();
        rolesTab = new RolesTab();

        sheet.addTab( permissionsTab, "User management space." );
        sheet.getTab( 0 ).setId( "UserManagement" );

        sheet.addTab( rolesTab, "New user registration space." );
        sheet.getTab( 1 ).setId( "UserRegistration" );

        sheet.addTab( roleManagementForm, "New user registration space." );
        sheet.getTab( 2 ).setId( "UserRegistration" );

        verticalLayout.addComponent( sheet );
        editableHeights();
        // TODO add user code here
    }


    @AutoGenerated
    void editableHeights()
    {
        VerticalLayout layout = new VerticalLayout();
        // BEGIN-EXAMPLE: component.table.editable.editableheights
        // Table with some typical data types
        final Table table = new Table( "Edible Table" );
        table.addContainerProperty( "Name", String.class, null );
        table.addContainerProperty( "Login", String.class, null );
        table.addContainerProperty( "Password", PasswordField.class, null );
        table.addContainerProperty( "Email", String.class, null );
        table.addContainerProperty( "Role", String.class, null );
        table.setDescription( "All users registered in shiro" );
        table.setWidth( "80.0%" );
        table.setHeight( "-1px" );
        table.setImmediate( true );

        // Some example data
        //TODO Retrieve users from database
        Object people[][] = {
                { "Galileo", "galileo", new PasswordField(), "galileo@mail.com", "Admin" },
                { "Monnier", "monnier", new PasswordField(), "monnier@mail.com", "User" },
                { "Oterma", "oterma", new PasswordField(), "oterma@mail.com", "User" },
                { "Valtaoja", "valtaoja", new PasswordField(), "valtaoja@mail.com", "User" }
        };

        // Insert the data
        for ( int i = 0; i < people.length; i++ )
        {
            Object name = people[i][0];
            Object login = people[i][1];
            Object password = people[i][2];
            Object email = people[i][3];
            Object role = people[i][4];
            Object obj[] = {
                    name, login, password, email, role
            };
            table.addItem( obj, i );
        }
        table.setPageLength( table.size() );

        // Set a custom field factory that overrides the default factory
        table.setTableFieldFactory( new DefaultFieldFactory()
        {
            private static final long serialVersionUID = -3301080798105311480L;


            @Override
            public Field<?> createField( Container container, Object itemId, Object propertyId, Component uiContext )
            {
                if ( "Role".equals( propertyId ) )
                {
                    ComboBox select = new ComboBox();
                    select.setImmediate( true );
                    select.setTextInputAllowed( false );
                    select.setRequired( true );
                    select.setNullSelectionAllowed( false );
                    select.addItem( "Admin" );
                    select.addItem( "User" );
                    return select;
                }

                return super.createField( container, itemId, propertyId, uiContext );
            }
        } );
        table.setEditable( true );
        // Allow switching to non-editable mode
        final CheckBox editable = new CheckBox( "Table is editable", true );
        editable.addValueChangeListener( new Property.ValueChangeListener()
        {
            private static final long serialVersionUID = 6291942958587745232L;


            public void valueChange( Property.ValueChangeEvent event )
            {
                table.setEditable( ( Boolean ) editable.getValue() );
            }
        } );
        editable.setImmediate( true );
        // END-EXAMPLE: component.table.editable.editableheights
        table.addStyleName( "editableexample" );
        layout.addComponent( editable );
        layout.addComponent( table );

        setCompositionRoot( layout );
    }


    @Override
    public void dispose()
    {

    }
}
