#! /bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# accumulo            This shell script takes care of stopping and starting 
#                     accumulo on a single server
# chkconfig: - 60 20
# description: Apache Accumulo: an implementation of Google's BigTable
# probe: false

#. /etc/rc.d/init.d/functions

# let's assume this file is symlinked in from accumulo distro bin directory
# otherwise reset the ACCUMULO_HOME setting

. /etc/accumulo/accumulo-env.sh
. /etc/profile

#pwd=`pwd -P`
#ACCUMULO_HOME=`cd $pwd/.. ; pwd -P`

ACCUMULO_HOME=$ACCUMULO_HOME

CMD_PATT="accumulo"
is_running()
{
	line1=$(ps aux | ps aux | grep "$1")
	if [ -n "$line1" ]; then
		pid=$(ps aux | ps aux | grep "$1" | awk '{print $2}')
		grep -Eq "$CMD_PATT" "/proc/$pid/cmdline" 2>/dev/null && return 1
		return 0
	else
		return 0
	fi
}

master(){
	is_running "org.apache.accumulo.start.Main [m]aster"
	case "$?" in
		0)
			echo "Master is NOT Running" ;;
		1)
			pid=$(ps aux | ps aux | grep "org.apache.accumulo.start.Main [m]aster" | awk '{print $2}')
			echo "Master is running with pid $pid" ;;	
		*)
		;;
	esac
}

tracer(){
	is_running "org.apache.accumulo.start.Main [t]racer"
	case "$?" in
		0)
			echo "Accumulo Tracer is NOT Running" ;;
		1)
			pid=$(ps aux | ps aux | grep "org.apache.accumulo.start.Main [t]racer" | awk '{print $2}')
			echo "Accumulo Tracer is running with pid $pid" ;;	
		*)
		;;
	esac
}

gc(){
	is_running "org.apache.accumulo.start.Main [g]c"
	case "$?" in
		0)
			echo "GC is NOT Running" ;;
		1)
			pid=$(ps aux | ps aux | grep "org.apache.accumulo.start.Main [g]c" | awk '{print $2}')
			echo "GC is running with pid $pid" ;;	
		*)
		;;
	esac
}

monitor(){
	is_running "org.apache.accumulo.start.Main [m]onitor"
	case "$?" in
		0)
			echo "Monitor is NOT Running" ;;
		1)
			pid=$(ps aux | ps aux | grep "org.apache.accumulo.start.Main [m]onitor" | awk '{print $2}')
			echo "Monitor is running with pid $pid" ;;	
		*)
		;;
	esac
}

tserver(){
	is_running "org.apache.accumulo.start.Main [t]server"
	case "$?" in
		0)
			echo "Tablet Server is NOT Running" ;;
		1)
			pid=$(ps aux | ps aux | grep "org.apache.accumulo.start.Main [t]server" | awk '{print $2}')
			echo "Tablet Server is running with pid $pid" ;;	
		*)
		;;
	esac
}

logger(){
	is_running "org.apache.accumulo.start.Main [l]ogger"
	case "$?" in
		0)
			echo "Logger is NOT Running" ;;
		1)
			pid=$(ps aux | ps aux | grep "org.apache.accumulo.start.Main [l]ogger" | awk '{print $2}')
			echo "Logger is running with pid $pid" ;;	
		*)
		;;
	esac
}
RETVAL=0
case "$1" in
   start)
        $ACCUMULO_HOME/bin/start-all.sh
        RETVAL=$?
   ;;
   stop)
        $ACCUMULO_HOME/bin/stop-all.sh
        RETVAL=$?
   ;;
   status)
        COUNT=`pgrep -f "$ACCUMULO_HOME.*org.apache.accumulo.start" | wc -l`
        echo "There are $COUNT accumulo processes on this machine"
	master
	tracer
	monitor
	gc
	logger
	tserver
   ;;
   restart)
        $0 stop
        $0 start
   ;;
   *)
      echo "Usage: $0 {start|stop|status|restart}"
      exit 1
   ;;
esac

exit 0
