#!/bin/bash


. /etc/subutai/config
. /etc/subutai/bsfl
init


# Function addmount:
# -----------------------------------------------------------------------------
# 
# Usage: 
# ======
#
# addmount master opt  lxc
# addmount master var  lxc-data
# addmount master home lxc-home
#
# Description:
# =============
#
# Mainly used by the master creation process to:
#
# o Creates a zfs dataset for an LXC mount point
# o Checks to make sure it is properly created and mounted
# o Adds the LXC mount entries to the lxc configuration file of container
# o Moves over data contained in the rootfs for the mount to the dataset
# o Snapshots the newly created populated filesystems with @template

function addmount {
  name=$1
  mount=$2
  zpool=$3

  dataset=$zpool/$name-$mount
  echo Creating $dataset dataset for $mount mount entry
  zfs create $dataset

  if [ -z "`zfs list $dataset`" ]; then
    echo Could not create $dataset dataset 
    exit 1
  else
    echo Created $dataset dataset, adding $mount mount entry
    echo lxc.mount.entry = /$dataset $mount none bind,rw 0 0 \
         >> /var/lib/lxc/$name/config
  fi
  echo Copying $mount data from rootfs to new $dataset dataset
  pushd .
  mountpath=/var/lib/lxc/$name/rootfs/$mount
  cd $mountpath

  if [ -n "`ls -A $mountpath`" ]; then
    # We use tar to preserve permissions: do NOT use cp or mv
    tar -c * | tar -x -C /$dataset
    echo Deleting $mount contents from rootfs
    rm -rf /var/lib/lxc/$name/rootfs/$mount/*
  else
    echo Nothing within $mountpath, abandoning copy
  fi

  popd

  # Time to Snapshot and Apply Holds
  zfs snapshot $dataset'@template'
  zfs hold keep $dataset'@template'
  return
}


function check_exists {
  container="$1"
  usage="$2"

  if [ -z "$container" ]; then
    msg_error "No value provided for containe's name. Aborting ..."
    show_usage "$usage"
  fi

  if [ -z "`lxc-ls "$container" | grep "$container"`" ]; then
    msg_error "Container \"$container\" does not exist. Aborting ..."
    show_usage "$usage"
  else 
    msg_ok "Container \"$container\" exists."
  fi
}


function check_missing {
  container="$1"
  usage="$2"

  if [ -z "$container" ]; then
    msg_error "No value provided for containe's name. Aborting ..."
    show_usage "$usage"
  fi

  if [ -n "`lxc-ls "$container" | grep "$container"`" ]; then
    msg_error "Container \"$container\" exists. Aborting ..."
    show_usage "$usage"
  else 
    msg_ok "Container \"$container\" does not exist."
  fi
}


function check_parent {
  parent="$1"
  usage="$2"

  if [ -z "$parent" ]; then 
    msg_error "No value provided for parent container. Aborting ..."
    show_usage "$usage"
  fi

  if [ -z "`lxc-ls "$parent" | grep "$parent"`" ]; then 
    msg_error "Parent container \"$parent\" does not exist. Aborting ..."
    show_usage "$usage"
  else
    msg_ok "Parent container \"$parent\" exists."
  fi
}


function check_child {
  child="$1"
  usage="$2"

  if [ -z "$child" ]; then 
    msg_error "No value provided for child container. Aborting ..."
    show_usage "$usage"
  fi

  if [ -n "`lxc-ls "$child" | grep "$child"`" ]; then 
    msg_error "Child container \"$child\" already exists. Aborting ..."
    show_usage "$usage"
  else
    msg_ok "Child container \"$child\" does not exist."
  fi
}


# URGENT: this is a stub function and needs to be properly implemented
# this function needs to ask Subutai if a template name is registered 
# already. Since this functionality is not available I just stubbed it 
# out with a call to is_template. 
function is_registered {
  echo `is_template $1`
}


# URGENT: this is a stub function and needs to be properly implemented
# this function needs to take the supplied tsar file and upload and 
# register it with the Subutai management server.
function send_n_register {
  tsar=$1

  msg_ok "TSAR file $tsar registered and sent to management server"
}


# checks if the container (arg $1) is a template, echo "true"/"false"
function is_template {
  c="$1"
  s=`zfs list -t snapshot -o name -H | grep "lxc/$c@template" | grep -v '\-opt'`

  if [ -z "$s" ]; then
    echo false
  else
    echo true
  fi
}

# gets the parent of a container
# first argument $1 is the name of the child container
function get_parent {
  c="$1"

  if [ "$c" == "master" ]; then
    echo master
    return 1
  fi

  snap=`zfs get origin -o value -H lxc/$c`
  echo `ctnr_from_ds $snap`
}

# extracts the container name from a dataset or a dataset snapshot
function ctnr_from_ds {
  ds="$1"
  echo $ds | sed -e 's/lxc.*\///' -e 's/@.*//' -e 's/-.*//'
}

# extracts the zpool name from a dataset or a dataset snapshot
function pool_from_ds {
  ds="$1"
  echo $ds | sed -e 's/\/.*//'
}

# extracts the snapshot name from a dataset snapshot
function snap_from_ds {
  ds="$1"
  echo $ds | sed -e 's/.*@//'
}

# extracts the partition name from a dataset or a dataset snapshot
function part_from_ds {
  ds="$1"
  echo $ds | sed -e 's/lxc.*\///' -e 's/@.*//' -e 's/.*-//'
}


# lists all the templates available
function list_templates {
  for line in `zfs list -t snapshot -o name -H \
    | grep template               \
    | egrep -v '\-.*'`; do
    echo `ctnr_from_ds $line`
  done
}


function clone-mount {
  child="$1"
  parent="$2"
  partition="$3"
  pool="$4"

  child_ds="$pool/$child-$partition"
  child_conf="/var/lib/lxc/$child/config"
  parent_ds="$pool/$parent-$partition"

  zfs clone "$parent_ds@template" "$child_ds"
  msg_info "    - \"$child_ds\" cloned from \"$parent_ds@template\""

  child_conf_new=$child_conf".new"
  parent_part="$parent-$partition"
  child_part="$child-$partition"
  cat "$child_conf" | sed -e "s/$parent_part/$child_part/" > "$child_conf_new"
  mv -f "/var/lib/lxc/$child/config" "/var/lib/lxc/$child/config.old"
  mv "/var/lib/lxc/$child/config.new" "/var/lib/lxc/$child/config"
}


function clone_lxc {
  parent="$1"
  child="$2"
  usage="$3"

  # Clone Plan
  # --------------------------------------------------------------------------
  # (1) perform sanity checks
  #       - check that child does NOT exist
  #       - check that parent does exist
  #       - check that parent is a template
  # (2) copy over config and fstab files, and mkdir for rootfs
  # (3) massage the utsname and other lxc properties
  # (4) zfs clone $pool/$parent_ds@template $pool/$child_ds
  # (5) zfs set mountpoint=/var/lib/lxc/$child/rootfs $pool/$child_ds
  # (6) handle creation of external file system mounts
  # (7) alter hostname from /etc/hosts and /etc/hostname

  # (1) perform sanity checks
  check_missing $child "`usage`" 
  check_exists $parent "`usage`"

  if [ "`is_template $parent`" == "false" ]; then
    msg_notice "    - parent \"$parent\" is not a template ... promoting"
    subutai-template $parent
  else
    msg_info "    - parent \"$parent\" is a template"
  fi

  # (2) copy over config and fstab files, and mkdir for rootfs
  parent_home=/var/lib/lxc/$parent
  child_home=/var/lib/lxc/$child
  child_rootfs=$child_home/rootfs
  child_conf=$child_home/config
  child_conf_new="$child_conf".new
  child_conf_old="$child_conf".old

  mkdir $child_home
  # (3) massage the utsname and other lxc and filesystem mounts
  cat $parent_home/config                                          | \
     sed -e "s/lxc\.utsname.*/lxc\.utsname = $child/"                \
         -e "s/\/var\/lib\/lxc\/$parent/\/var\/lib\/lxc\/$child/g" > $child_home/config
  cp $parent_home/fstab $child_home
  mkdir $child_home/rootfs

  # (4) zfs clone $pool/$parent_ds@template $pool/$child_ds
  zfs clone lxc/$parent@template lxc/$child

  # (5) zfs set mountpoint=/var/lib/lxc/$child/rootfs $pool/$child_ds
  zfs set mountpoint=/var/lib/lxc/$child/rootfs lxc/$child
  
  # (6) Handle creation of external file system mounts
  clone-mount $child $parent opt lxc
  clone-mount $child $parent var lxc-data
  clone-mount $child $parent home lxc-data

  # (7) alter hostname from /etc/hosts and /etc/hostname
  echo $child > $child_rootfs/etc/hostname
  cat $parent_home/rootfs/etc/hosts | sed -e "s/$parent/$child/g" > $child_rootfs/etc/hosts
}


