#!/bin/bash
set -e
. /etc/profile
if [ "x$JAVA_HOME" == "x" ]; then
  JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
fi
export JAVA_HOME=$JAVA_HOME

stormHome="/opt/storm-0.8.2"
stormConf="/etc/storm"

if [[ "x$STORM_HOME" != "x" ]];
then
        stormHome=$STORM_HOME
fi

if [[ "x$STORM_CONF_DIR" != "x" ]];
then
        stormConf=$STORM_CONF_DIR
fi

# Create symlink to configuration files
ln -sf $stormConf/* $stormHome/conf/

#Install ZeroMQ(Storm Native Dependency)
cd /opt/zeromq-2.1.7
./configure
make
make install

# Install JZMQ(Storm Native Dependency)
cd /opt/jzmq
./autogen.sh
./configure
cd /opt/jzmq/src
touch classdist_noinst.stamp
CLASSPATH=.:./.:$CLASSPATH javac -d . org/zeromq/ZMQ.java org/zeromq/ZMQException.java org/zeromq/ZMQQueue.java org/zeromq/ZMQForwarder.java org/zeromq/ZMQStreamer.java
cd /opt/jzmq
make
make install
