#!/bin/bash
set -e

. /etc/profile

#Remove ZeroMQ home directory
if [ -d "/opt/zeromq-2.1.7" ]; then
	rm -r /opt/zeromq-2.1.7
fi

#Remove JZMQ home directory
if [ -d "/opt/jzmq" ]; then
        rm -r /opt/jzmq
fi

#Remove Storm home directory
if [ -d "/opt/storm-0.8.2" ]; then
        rm -r /opt/storm-0.8.2
fi
# Remove Storm related folders
if [ -d "/var/stormtmp" ]; then
        rm -r /var/stormtmp
fi
