#!/bin/bash

# Code copied from dh_systemd_enable ----------------------
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask management.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled management.service; then
        # Enables the unit on first installation, creates new
        # symlinks on upgrades if the unit file has changed.
        deb-systemd-helper enable management.service >/dev/null || true

        # change currenttimezone
        echo "Etc/UTC" > /etc/timezone
        # configure networking
        sed -i /etc/network/interfaces -e 's/iface eth0 inet dhcp/iface eth0 inet static\naddress 10.10.10.1\nnetmask 255.255.255.0\ngateway 10.10.10.254\ndns-search intra.lan\ndns-nameservers 10.10.10.254/g'
        # Change default password
        sed -i /etc/shadow -e '1 s/^.*$/root:$6$s095rK7.$0bqNwLNnABaQ8LKR\/mSFJfHTlW24Xg.6uUv5Wt50NaV3b\/xAH6kYJyx7vaOrAZzsBTH1t1iU2WvQ2buCrVDL50:16928:0:99999:7:::/g'
        # Enable password login via ssh
        sed -i /etc/ssh/sshd_config -e 's/PermitRootLogin prohibit-password/PermitRootLogin yes/g'
else
        # Update the statefile to add new symlinks (if any), which need to be
        # cleaned up on purge. Also remove old symlinks.
        deb-systemd-helper update-state management.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
    deb-systemd-invoke start management.service >/dev/null || true
fi