#!/bin/sh
set -e

# Code copied from dh_systemd_enable ----------------------
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask management.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge management.service >/dev/null
		deb-systemd-helper unmask management.service >/dev/null
	fi
fi
# End code copied from dh_systemd_enable ------------------

