package io.subutai.core.peer.impl;


public enum RecipientType
{
    COMMAND_REQUEST, COMMAND_RESPONSE, CREATE_CONTAINER_GROUP_REQUEST, CONTAINER_CREATE_REQUEST, PEER_REQUEST_LISTENER,
    PEER_RESPONSE_LISTENER, ECHO_LISTENER, CONTAINER_DESTROY_REQUEST, DESTROY_ENVIRONMENT_CONTAINER_GROUP_REQUEST,
    CREATE_ENVIRONMENT_CONTAINER_GROUP_REQUEST
}
