Document: subutai-cli-dev
Title: Debian subutai-cli-dev Manual
Author: <insert document author here>
Abstract: This manual describes what subutai-cli-dev is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/subutai-cli-dev/subutai-cli-dev.sgml.gz

Format: postscript
Files: /usr/share/doc/subutai-cli-dev/subutai-cli-dev.ps.gz

Format: text
Files: /usr/share/doc/subutai-cli-dev/subutai-cli-dev.text.gz

Format: HTML
Index: /usr/share/doc/subutai-cli-dev/html/index.html
Files: /usr/share/doc/subutai-cli-dev/html/*.html
