#!/bin/bash
# Starts and stops Zookeeper.
if [ "x$ZOOKEEPER_HOME" = "x" ];
then
	ZOOKEEPER_HOME=/opt/zookeeper-3.4.5
fi

case "$1" in
start)
	start-stop-daemon --start --exec $ZOOKEEPER_HOME/bin/zookeeper.sh start
;;

stop)
	start-stop-daemon --start --exec $ZOOKEEPER_HOME/bin/zookeeper.sh stop
;;

restart)
        $0 stop
        $0 start
;;

status)
        line=$(ps aux | grep [Q]uorumPeerMain)
        if [ -n "$line" ]; then
                echo "Zookeeper is Running"
                exit 0
        else
                echo "Zookeeper is NOT Running"
                exit 1
        fi
;;

*)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac
