#!/bin/bash
# Starts and stops hadoop cluster.

if [ "x$HADOOP_HOME" = "x" ];
then
  HADOOP_HOME=/opt/hadoop-1.2.1
fi
case "$1" in
start)
  start-stop-daemon --start --exec $HADOOP_HOME/bin/start-all.sh
;;
stop)
  start-stop-daemon --start --exec $HADOOP_HOME/bin/stop-all.sh
;;
restart)
  $0 stop
  $0 start
;;
status)
  service hadoop-dfs status
  service hadoop-mapred status
;;
*)
  echo "Usage: $0 {start|stop|restart|status}"
  exit 1
esac

