#!/bin/sh 
set -e
# Remove Sqoop Files and Folders
if [ -d "/opt/sqoop-1.4.3" ]; then
	rm -r /opt/sqoop-1.4.3
fi

#Remove paths and exports from relevant files
FilePath="/etc/profile"

if [ -f "/etc/profile.d/sqoop-home.sh" ]; then
	rm /etc/profile.d/sqoop-home.sh
fi
. $FilePath
