#!/bin/bash
set -e 
FilePath="/etc/profile"

. $FilePath

sqoopVersion=1.4.4
sqoopHome="/opt/sqoop-$sqoopVersion"
sqoopConf="/etc/sqoop"

if [[ "x$SQOOP_HOME" != "x" ]];
then
        sqoopHome=$SQOOP_HOME
fi

if [[ "x$SQOOP_CONF_DIR" != "x" ]];
then
        sqoopConf=$SQOOP_CONF_DIR
fi


# Create symlink to configuration files and scripts
ln -sf $sqoopConf/* $sqoopHome/conf/
