#!/bin/bash 
set -e

sqoopVersion=1.4.4
# Remove Sqoop Files and Folders
if [ -d "/opt/sqoop-$sqoopVersion" ]; then
	rm -r /opt/sqoop-$sqoopVersion
fi

#Remove paths and exports from relevant files
FilePath="/etc/profile"

if [ -f "/etc/profile.d/sqoop-home.sh" ]; then
	rm /etc/profile.d/sqoop-home.sh
fi
. $FilePath
