#!/bin/bash 
set -e
# Remove Accumulo Files and Folders
if [ -d "/opt/accumulo-1.6.0" ]; then
	rm -r /opt/accumulo-1.6.0
fi

#Remove paths and exports from relevant files
FilePath="/etc/profile"

if [ -f "/etc/profile.d/accumulo-home.sh" ]; then
	rm /etc/profile.d/accumulo-home.sh
fi

. $FilePath
