#!/bin/sh 
set -e
FilePath="/etc/profile"
accumuloHomeEcho="/opt/accumulo-1.4.2"
accumuloPath="\/opt\/accumulo-1.4.2\/bin"
accumuloPathEcho=$accumuloHomeEcho"/bin"
accumuloConf=$accumuloHomeEcho"/conf"

if grep -q "ACCUMULO_HOME=" $FilePath
then
        echo "ACCUMULO_HOME is already added!"
else
        echo "ACCUMULO_HOME is being inserted"
        echo "export ACCUMULO_HOME="$accumuloHomeEcho >> $FilePath
fi

if grep -q "export PATH=" $FilePath
then
        if grep -q "${accumuloPath}" $FilePath
        then
                echo "ACCUMULO is already inserted to PATH!!!"
        else
                echo "ACCUMULO is being insterted to PATH!"
                sed -i "s/export PATH=/export PATH=$accumuloPath:/1" $FilePath
        fi
else
        echo "export PATH=$PATH:$accumuloPathEcho" >> "${FilePath}"
fi

if [ "x$JAVA_HOME" = "x" ];
then
	$accumuloHomeEcho/bin/accumulo-property.sh JAVA_HOME /usr/lib/jvm/java-1.7.0-openjdk-amd64
else
	$accumuloHomeEcho/bin/accumulo-property.sh JAVA_HOME $JAVA_HOME 
fi

if [ "x$HADOOP_HOME" = "x" ];
then
	$accumuloHomeEcho/bin/accumulo-property.sh HADOOP_HOME /opt/hadoop-1.2.1
else
        $accumuloHomeEcho/bin/accumulo-property.sh HADOOP_HOME $HADOOP_HOME
fi

if [ "x$ZOOKEEPER_HOME" = "x" ];
then
        $accumuloHomeEcho/bin/accumulo-property.sh ZOOKEEPER_HOME /opt/zookeeper-3.4.5
else
        $accumuloHomeEcho/bin/accumulo-property.sh ZOOKEEPER_HOME $ZOOKEEPER_HOME
fi

if [ "x$ACCUMULO_LOG_DIR" = "x" ];
then
        $accumuloHomeEcho/bin/accumulo-property.sh ACCUMULO_LOG_DIR /opt/accumulo-1.4.2/log 
else
        $accumuloHomeEcho/bin/accumulo-property.sh ACCUMULO_LOG_DIR $ACCUMULO_LOG_DIR
fi
