#!/bin/bash


. /etc/lsb-release

. $subutai_conf_base/config
. $subutai_lib_base/bsfl
init

. $subutai_lib_base/reg_ops
. $subutai_lib_base/zfs_ops
. $subutai_lib_base/lxc_ops
. $subutai_lib_base/git_ops
. $subutai_lib_base/deb_ops
. $subutai_lib_base/lock_ops
. $subutai_lib_base/ovs_ops
. $subutai_lib_base/monitor_ops
# Function addmount:
# -----------------------------------------------------------------------------
# 
# Usage: 
# ======
#
# addmount master opt  lxc
# addmount master var  lxc-data
# addmount master home lxc-home
#
# Description:
# =============
#
# Mainly used by the master creation process to:
#
# o Creates a zfs dataset for an LXC mount point
# o Checks to make sure it is properly created and mounted
# o Adds the LXC mount entries to the lxc configuration file of container
# o Moves over data contained in the rootfs for the mount to the dataset
# o Snapshots the newly created populated filesystems with @template

function addmount {
  fs_addmount $1 $2 $3
}

