#!/bin/bash

# ==========================================================================
# Set of functions that process locking functionality with a mix of utility
# functions.
# ==========================================================================

function lock_subutai_system {
  mkdir -p $SUBUTAI_LOCK_PATH
  touch $SUBUTAI_LOCK_PATH/system_lock
}

function unlock_subutai_system {
  if [ -f "$SUBUTAI_LOCK_PATH/system_lock" ]; then
    rm $SUBUTAI_LOCK_PATH/system_lock
  fi
}

function is_system_locked {
  ls $SUBUTAI_LOCK_PATH/system_lock > /dev/null 2>&1
  if [ $? == 0 ]
  then
    echo "true"
  else
    echo "false"
  fi
}

function is_system_all_locked {
  (ls $SUBUTAI_LOCK_PATH/system_lock || ls $SUBUTAI_LOCK_PATH/write/*) \
    > /dev/null 2>&1
  if [ $? == 0 ]
  then
    echo "true"
  else
    echo "false"
  fi
}

function lock_container_write {
  mkdir -p $SUBUTAI_LOCK_PATH/write/
  touch $SUBUTAI_LOCK_PATH/write/$1-$2
  echo $$ > $SUBUTAI_LOCK_PATH/write/$1-$2
}

function lock_container_read {
  mkdir -p $SUBUTAI_LOCK_PATH/read/
  touch $SUBUTAI_LOCK_PATH/read/$1-$2
  echo $$ > $SUBUTAI_LOCK_PATH/read/$1-$2
}

function unlock_container_write {
  if [ -d "$SUBUTAI_LOCK_PATH/write" ]; then
    removing=`ls $SUBUTAI_LOCK_PATH/write/ | grep -e "\b$1\b"`
    rm $SUBUTAI_LOCK_PATH/write/$removing  > /dev/null 2>&1
  fi
}

function unlock_container_read {
  if [ -d "$SUBUTAI_LOCK_PATH/write" ]; then
    removing=`ls $SUBUTAI_LOCK_PATH/write/ | grep -e "\b$1\b"`
    rm $SUBUTAI_LOCK_PATH/write/$removing > /dev/null 2>&1
  fi
  if [ -d "$SUBUTAI_LOCK_PATH/read" ]; then
    removing=`ls $SUBUTAI_LOCK_PATH/read/ | grep -e "\b$1\b"`
    rm $SUBUTAI_LOCK_PATH/read/$removing > /dev/null 2>&1
  fi
}

function are_containers_readable {
  if [[ -z "$2" ]]
  then
    src_container=$1
    wipe_outstanding_locks $src_container
    (ls $SUBUTAI_LOCK_PATH/read/ | grep -e "\b$src_container\b") > /dev/null 2>&1
    if [ $? == 0 ]
    then
      echo "true"
    else
      echo "false"
    fi
  else
    src_container=$1
    dst_container=$2
    wipe_outstanding_locks $src_container $dst_container
    (ls $SUBUTAI_LOCK_PATH/read/ | grep -e "\b$src_container\b" \
     || ls $SUBUTAI_LOCK_PATH/read/ | grep -e "\b$dst_container\b") \
      > /dev/null 2>&1
    if [ $? == 0 ]
    then
      echo "true"
    else
      echo "false"
    fi
  fi
}

function are_containers_writable {
  if [[ -z "$2" ]]
  then
    src_container=$1
    wipe_outstanding_locks $src_container
    (ls $SUBUTAI_LOCK_PATH/write/ | grep -e "\b$src_container\b" \
     || ls $SUBUTAI_LOCK_PATH/read/ | grep -e "\b$src_container\b") > /dev/null 2>&1
    if [ $? == 0 ]
    then
      echo "true"
    else
      echo "false"
    fi
  else
    src_container=$1
    dst_container=$2
    wipe_outstanding_locks $1 $2
    (ls $SUBUTAI_LOCK_PATH/write/ | grep -e "\b$src_container\b" \
     || ls $SUBUTAI_LOCK_PATH/write/ | grep -e "\b$dst_container\b" \
     || ls $SUBUTAI_LOCK_PATH/read/ | grep -e "\b$dst_container\b" \
     || ls $SUBUTAI_LOCK_PATH/read/ | grep -e "\b$dst_container\b") \
      > /dev/null 2>&1
    if [ $? == 0 ]
    then
      echo "true"
    else
      echo "false"
    fi
  fi
}

function wipe_outstanding_locks {
  if [[ -z "$2" ]]
  then
    src_container=$1
    wipe_outstanding_read_locks $src_container
    wipe_outstanding_write_locks $src_container
  else
    src_container=$1
    dst_container=$2
    wipe_outstanding_read_locks $src_container $dst_container
    wipe_outstanding_write_locks $src_container $dst_container
  fi
}

function wipe_outstanding_read_locks {
  if [[ -z "$2" ]]
  then
    target_container=$1-
  else
    target_container=$1-$2
  fi
  for lockfile in $SUBUTAI_LOCK_PATH/read/$target_container;
  do
    if [ ! -e $lockfile ]
    then
      continue
    fi
    process_id=`cat $lockfile`
    if [ "`ps -p $process_id -o comm=`" == "" ]
    then
      rm $lockfile
    fi
  done
}

function wipe_outstanding_write_locks {
  if [[ -z "$2" ]]
  then
    target_container=$1-
  else
    target_container=$1-$2
  fi
  for lockfile in $SUBUTAI_LOCK_PATH/write/$target_container;
  do
    if [ ! -e $lockfile ]
    then
      continue
    fi
    process_id=`cat $lockfile`
    if [ "`ps -p $process_id -o comm=`" == "" ]
    then
      rm $lockfile
    fi
  done
}
