#!/bin/bash

# ==========================================================================
# Set of functions that provides functionality to run pre and post
# execution scripts
# ==========================================================================


function execute_prescripts {
  local scripts="$1"
  local lxc="$2"
  if [ -z "$scripts" ]; then
    msg_error "No arguments provided to ${FUNCNAME[0]}! Aborting.."
    exit 1
  fi

  msg_info "    - ${FUNCNAME[0]} $scripts"

  IFS=' ' read -a scriptArray <<< "$scripts"
  for script in "${scriptArray[@]}"
  do
    # Remove unnecessary whitespaces if any
    script=$(echo " $script " | tr -d ' ')
    run_script "$subutai_pre_script_base/$script"
  done
}


function execute_all_prescripts {
  local binding=$1
  local lxc="$2"
  if [ -z "$binding" ]; then
    msg_error "No binding passed to ${FUNCNAME[0]}! Aborting.."
    exit 1
  fi

  msg_info "    - ${FUNCNAME[0]} for $binding"

  #Initialize scripts with all the scripts under subutai_pre_script_base 
  # starting with pre-${FUNCNAME[0]}
  shopt -s nullglob
  scriptArray=($subutai_pre_script_base/pre-$binding*)
  for script in "${scriptArray[@]}"
  do
    # Remove unnecessary whitespaces if any
    script=$(echo " $script " | tr -d ' ')
    run_script "$script"
  done
}


function execute_postscripts {
  local scripts="$1"
  local lxc="$2"
  if [ -z "$scripts" ]; then
    msg_error "No arguments provided to ${FUNCNAME[0]}! Aborting.."
    exit 1
  fi

  msg_info "    - ${FUNCNAME[0]} $scripts"

  IFS=' ' read -a scriptArray <<< "$scripts"
  for script in "${scriptArray[@]}"
  do
    # Remove unnecessary whitespaces if any
    script=$(echo " $script " | tr -d ' ')
    run_script "$subutai_post_script_base/$script"
  done
}


function execute_all_postscripts {
  local binding=$1
  local lxc="$2"
  if [ -z "$binding" ]; then
    msg_error "No binding passed to ${FUNCNAME[0]}! Aborting.."
    exit 1
  fi

  msg_info "    - ${FUNCNAME[0]} for $binding"

  #TODO initialize scripts with all the scripts under subutai_pre_script_base 
  # starting with pre-${FUNCNAME[0]}
  scriptArray=($subutai_post_script_base/post-$binding*)
  for script in "${scriptArray[@]}"
  do
    # Remove unnecessary whitespaces if any
    script=$(echo " $script " | tr -d ' ')
    run_script "$script"
  done
}

function run_script {
  script_directory=$1
  if [ -z $script_directory ]; then
    msg_error "script directory is not provided. Aborting!"
    exit 1
  fi
  message="      - running $script"
  $script_directory > /dev/null
  local status=$?
  if [ $status == "0" ];then
    msg_info "$message"
  else
    msg_error "$message"
    exit 1
  fi
}
