#!/bin/bash

# ==========================================================================
# Set of functions for quota functionality
# ==========================================================================


# returns maximum amount of memory on physical machine
# that can be given to the specified container
# in megabytes
function get_total_usable_ram_in_megabytes {
  local container=$1
  lxc_assert $container > /dev/null

  local total_usable_ram_in_bytes=$(get_total_usable_ram $container)
  local result=$(echo $total_usable_ram_in_bytes/\(1024*1024\) | bc)
  echo $result"M"
  return
}


# returns maximum amount of memory on physical machine
# that can be given to the specified container
# in bytes
function get_total_usable_ram {
  local container=$1
  lxc_assert $container > /dev/null

  local container_ram_usage=$(get_used_ram $container)
  local total_available_ram=$(get_physical_available_ram)

  local result=$(echo $container_ram_usage + $total_available_ram | bc)
  echo "$result"
  return
}
