#!/bin/bash

# --------------------------------------------------------------------------
# Bunch-O ZFS convenience operations
# --------------------------------------------------------------------------


# returns the children of the provided container(arg $1)
function zfs_get_children_list {
  local parent="$1"
  local snap=

  # we got a dataset instead of a clone name
  if [ -n "`echo $parent | egrep 'lxc.*/'`" ]; then
    snap="$parent@template"
  else
    snap="lxc/$parent@template"
  fi
  local count=0
  for ds in `zfs get origin | grep $snap | awk '{print $1}' | grep -v $snap`
  do
    children_list[$count]=`zfs_ctnr_from_ds $ds`
    count=`expr $count + 1`
  done

  echo ${children_list[*]}
}


# prints out the children for a ds or container name (arg $1)
# counts and prints out the children
# returns the child count
function zfs_get_children {
  local parent="$1"
  local snap=

  # we got a dataset instead of a clone name
  if [ -n "`echo $parent | egrep 'lxc.*/'`" ]; then 
    snap="$parent@template"
  else
    snap="lxc/$parent@template"
  fi

  local count=0
  for ds in `zfs get origin | grep $snap | awk '{print $1}' | grep -v $snap`
  do
    msg_info "        -> \"`zfs_ctnr_from_ds $ds`\" is a child of $parent"
    count=`expr $count + 1`
  done

  return $count
}


# assert snapshot (arg $1) does NOT exist, if it does show usage (arg $2)
# warning: exits!
function zfs_assert_nosnap {
  local snap="$1"
  local usage="$2"

  if [ "$snap" == "`zfs list -t snapshot -o name -H $snap`" ]; then
    msg_error "Snapshot \"$snap\" already exists!"
    show_usage "$usage"
  fi
}


# assert snapshot (arg $1) exists, if it does NOT show usage (arg $2)
# warning: exits!
function zfs_assert_snap {
  local snap="$1"
  local usage="$2"

  if [ -z "`zfs list -t snapshot -o name -H $snap`" ]; then
    msg_error "Snapshot \"$snap\" does NOT exist!"
    show_usage "$usage"
  fi
}


# assert dataset (arg $1) does NOT exist, if it does show usage (arg $2)
# warning: exits!
function zfs_assert_nods {
  local ds="$1"
  local usage="$2"

  if [ -n "`zfs list -o name -H | grep $ds`" ]; then
    msg_error "ZFS dataset \"$ds\" already exists!"
    show_usage "$usage"
  fi
}


# assert dataset (arg $1) exists, if it does NOT show usage (arg $2)
# warning: exits!
function zfs_assert_ds {
  local ds="$1"
  local usage="$2"

  if [ -z "`zfs list -o name -H $ds`" ]; then
    msg_error "ZFS dataset \"$ds\" does NOT exist!"
    show_usage "$usage"
  fi
}


# checks if the container (arg $1) is a template, echo "true"/"false"
function zfs_is_template {
  local c="$1"
  if [ -z "`zfs list -t snapshot -o name -H | grep "lxc/$c@template"`" ]; then
    echo false
  else
    echo true
  fi
}


# gets the parent of a container
# first argument $1 is the name of the child container
# master returns master
function zfs_get_parent {
  local c="$1"

  if [ "$c" == "master" ]; then
    echo master
    return
  fi

  local snap=`zfs get origin -o value -H lxc/$c`
  echo `zfs_ctnr_from_ds $snap`
}


# extracts the container name from a dataset or a dataset snapshot
function zfs_ctnr_from_ds {
  local ds="$1"
  echo $ds | sed -e 's/lxc.*\///' -e 's/@.*//' -e 's/-.*//'
}


# extracts the zpool name from a dataset or a dataset snapshot
function zfs_pool_from_ds {
  local ds="$1"
  echo $ds | sed -e 's/\/.*//'
}


# extracts the snapshot name from a dataset snapshot
function zfs_snap_from_ds {
  local ds="$1"
  echo $ds | sed -e 's/.*@//'
}


# extracts the partition name from a dataset or a dataset snapshot
function zfs_part_from_ds {
  local ds="$1"
  echo $ds | sed -e 's/lxc.*\///' -e 's/@.*//' -e 's/.*-//'
}


# lists all the templates available
function zfs_list_templates {
  for l in `zfs list -t snapshot -o name -H | grep @template | grep -v -`; do
    echo `zfs_ctnr_from_ds $l`
  done
}

function zfs_copy_ds {
  local from_ds="$1"

  if [ -n "`echo $from_ds | grep -`" ]; then
    local from_part="`zfs_part_from_ds $from_ds`"
  else
    local from_part=""
  fi

  local from_pool="`zfs_pool_from_ds $from_ds`"
  local from_lxc="`zfs_ctnr_from_ds $from_ds`"
  local parent_lxc="`zfs_get_parent $from_lxc`"
  local to_ds="$2"

  if [ -z "$from_part" ]; then 
    local parent_ds="$from_pool/$parent_lxc"
  else
    local parent_ds="$from_pool/$parent_lxc-$from_part"
  fi

  local parent_snap="$parent_ds@template"

  # make sure the from_ds exists and the to_ds does not
  zfs_assert_ds "$from_ds"
  zfs_assert_nods "$to_ds"
  zfs_assert_ds "$parent_ds"
  zfs_assert_snap "$parent_snap"

  local now=`date +"%m_%d_%Y"`
  local from_snap="$from_ds@$now"

  zfs snapshot "$from_snap"
  local stream="$SUBUTAI_TMPDIR/$parent_lxc$from_lxc$now"
  zfs send -I "$parent_snap" "$from_snap" > "$stream"
  zfs recv "$to_ds" < "$stream"

  # cleanup
  rm "$stream"
  zfs destroy "$from_snap"
  zfs destroy "$to_ds@$now"
}

