package io.subutai.core.localpeer.impl;


public enum RecipientType
{
    COMMAND_REQUEST, COMMAND_RESPONSE, PEER_REQUEST_LISTENER,
    PEER_RESPONSE_LISTENER, DESTROY_ENVIRONMENT_CONTAINER_GROUP_REQUEST,
    CREATE_ENVIRONMENT_CONTAINER_GROUP_REQUEST
}
