#!/bin/bash
SUBUTAI_HOME="/opt/subutai-management"
SUBUTAI_BIN="/usr/bin/subutai-management"
SUBUTAI_DATA="/var/log/subutai-management/data"
SUBUTAI_PID=$(pgrep -l -f karaf | grep java | awk '{print $1}')

subutaiGetPid(){
SUBUTAI_PID=$(pgrep -l -f karaf | grep java | awk '{print $1}')
}


case "$1" in
start)
        if [ -z "$SUBUTAI_PID" ];
        then
                sudo rm -rf $SUBUTAI_DATA/*
                sudo $SUBUTAI_BIN/start
                echo "Subutai-Management is starting.."
                sleep 1
                subutaiGetPid
                echo "Subutai-Management is started..($SUBUTAI_PID)"
        else
                echo "Subutai-Management is already running..($SUBUTAI_PID)"
        fi
;;
stop)
        if [ -z "$SUBUTAI_PID" ];
        then
                echo "Subutai-Management is not running now.."
        else
                echo "Subutai-Management is stopping now..($SUBUTAI_PID)"
                sudo $SUBUTAI_BIN/stop
        fi
        ;;
restart)
        echo "Subutai-Management is restarting now.."
        sudo $SUBUTAI_BIN/stop
        sudo rm -rf $SUBUTAI_DATA/*
        sudo $SUBUTAI_BIN/start
        subutaiGetPid
        echo "Subutai-Management is started..($SUBUTAI_PID)"
        ;;
status)
        if [ -z "$SUBUTAI_PID" ];
        then
                echo "Subutai-Management is not running now.."
        else
                echo "Subutai-Management is running now..($SUBUTAI_PID)"
        fi
        ;;
esac
