#!/bin/bash
if [ -z "$1" ]
  then
    echo "No argument provided"
    echo "First argument should be ip address of management host"
    echo "Optional second argument should be port to connect"
    echo "Examples: "
    echo "         node-approve 10.10.10.1"
    echo "         node-approve 10.10.10.1 8080"
    exit 1
fi

port="8443"
if [ -n "$2" ]
  then
    port=$2
    echo "Using custom $port to connect"
fi

sptoken=`curl -s --data "username=admin&password=secret" --insecure https://$1:$port/rest/v1/identity/gettoken`
rsp=`curl -s -k https://$1:$port/rest/v1/registration/requests?sptoken=$sptoken | awk -F"," -v k="\"id\": \"" '{
    gsub(/{|}/,"")
    for(i=1;i<=NF;i++){
        if ( $i ~ k ){
            print $i
        }
    }
}' | awk '{print $2 $4}' | tr -d ' ' | tr -d \"` 


arr=( $rsp )
for i in "${arr[@]}"; 
do 
curl -X POST -k https://$1:$port/rest/v1/registration/requests/$i/approve?sptoken=$sptoken;
echo Approved $i;
done

