#!/bin/bash 
set -e
# Remove Flume Files and Folders
if [ -d "/opt/flume-1.5.0" ]; then
	rm -r /opt/flume-1.5.0
fi

#Remove paths and exports from relevant files
FilePath="/etc/profile"

if [ -f "/etc/profile.d/flume-home.sh" ]; then
	rm /etc/profile.d/flume-home.sh
fi

. $FilePath
