#!/bin/bash 
set -e
FilePath="/etc/profile"

. $FilePath

flumeVersion=1.5.0
flumeConf="/etc/flume"
flumeHome="/opt/flume-$flumeVersion"

# Create symlink to configuration files
ln -sf $flumeConf/* $flumeHome/conf/
