#!/bin/bash
set -e

. /etc/profile

mongoConfDirectory="/etc/mongo"
originalMongoConfFile="/etc/mongodb.conf"

mkdir -p $mongoConfDirectory
if [ -f $originalMongoConfFile ]; then
        mv $originalMongoConfFile $mongoConfDirectory
fi

# Create symlink to configuration files
ln -sf $mongoConfDirectory/* /etc
