#!/bin/bash
set -e

. /etc/profile

mongoConfDirectory="/etc/mongo"
originalMongoConfFile="/etc/mongodb.conf"

mkdir -p $mongoConfDirectory
if [ -f $originalMongoConfFile ]; then
        cp $originalMongoConfFile $mongoConfDirectory
fi
